2020-05-07 18:53:36.698 | INFO | Telemetry Process | brokkr.inputs.modbus.ModbusSerialInput | Client details: {'method': 'rtu', 'socket': None, 'framer': <pymodbus.framer.rtu_framer.ModbusRtuFramer object at 0xb55a6650>, 'transaction': <pymodbus.transaction.DictTransactionManager object at 0xb55a6eb0>, '_debug': False, '_debugfd': None, 'broadcast_enable': False, 'port': '/dev/ttyAMA0', 'stopbits': 2, 'bytesize': 8, 'parity': 'N', 'baudrate': 9600, 'timeout': 2, '_strict': False, 'last_frame_end': None, '_t0': 0.0011458333333333333, 'inter_char_timeout': 0.00171875, 'silent_interval': 0.00401} (T+5340133 ms)
2020-05-07 18:53:36.699 | INFO | Telemetry Process | brokkr.inputs.modbus.ModbusSerialInput | Port details: {'device': '/dev/ttyAMA0', 'name': 'ttyAMA0', 'description': 'ttyAMA0', 'hwid': 'fe201000.serial', 'vid': None, 'pid': None, 'serial_number': None, 'location': None, 'manufacturer': None, 'product': None, 'interface': None, 'usb_device_path': None, 'device_path': '/sys/devices/platform/soc/fe201000.serial', 'subsystem': 'amba', 'usb_interface_path': None} (T+5340133 ms)
2020-05-07 18:53:46.697 | ERROR | Telemetry Process | pymodbus.client.sync | [Errno 13] could not open port /dev/ttyAMA0: [Errno 13] Permission denied: '/dev/ttyAMA0' (T+5350131 ms)
2020-05-07 18:53:46.698 | ERROR | Telemetry Process | brokkr.inputs.modbus.ModbusSerialInput | Error reading modbus data: Cannot connect to device /dev/ttyAMA0 - ttyAMA0 (T+5350132 ms)
2020-05-07 18:53:46.698 | INFO | Telemetry Process | brokkr.inputs.modbus.ModbusSerialInput | Client details: {'method': 'rtu', 'socket': None, 'framer': <pymodbus.framer.rtu_framer.ModbusRtuFramer object at 0xb55a69d0>, 'transaction': <pymodbus.transaction.DictTransactionManager object at 0xb55a6e30>, '_debug': False, '_debugfd': None, 'broadcast_enable': False, 'port': '/dev/ttyAMA0', 'stopbits': 2, 'bytesize': 8, 'parity': 'N', 'baudrate': 9600, 'timeout': 2, '_strict': False, 'last_frame_end': None, '_t0': 0.0011458333333333333, 'inter_char_timeout': 0.00171875, 'silent_interval': 0.00401} (T+5350132 ms)
2020-05-07 18:53:46.698 | INFO | Telemetry Process | brokkr.inputs.modbus.ModbusSerialInput | Port details: {'device': '/dev/ttyAMA0', 'name': 'ttyAMA0', 'description': 'ttyAMA0', 'hwid': 'fe201000.serial', 'vid': None, 'pid': None, 'serial_number': None, 'location': None, 'manufacturer': None, 'product': None, 'interface': None, 'usb_device_path': None, 'device_path': '/sys/devices/platform/soc/fe201000.serial', 'subsystem': 'amba', 'usb_interface_path': None} (T+5350133 ms)
2020-05-07 18:53:56.697 | ERROR | Telemetry Process | pymodbus.client.sync | [Errno 13] could not open port /dev/ttyAMA0: [Errno 13] Permission denied: '/dev/ttyAMA0' (T+5360131 ms)
2020-05-07 18:53:56.698 | ERROR | Telemetry Process | brokkr.inputs.modbus.ModbusSerialInput | Error reading modbus data: Cannot connect to device /dev/ttyAMA0 - ttyAMA0 (T+5360132 ms)
2020-05-07 18:53:56.698 | INFO | Telemetry Process | brokkr.inputs.modbus.ModbusSerialInput | Client details: {'method': 'rtu', 'socket': None, 'framer': <pymodbus.framer.rtu_framer.ModbusRtuFramer object at 0xb55a68b0>, 'transaction': <pymodbus.transaction.DictTransactionManager object at 0xb55a69b0>, '_debug': False, '_debugfd': None, 'broadcast_enable': False, 'port': '/dev/ttyAMA0', 'stopbits': 2, 'bytesize': 8, 'parity': 'N', 'baudrate': 9600, 'timeout': 2, '_strict': False, 'last_frame_end': None, '_t0': 0.0011458333333333333, 'inter_char_timeout': 0.00171875, 'silent_interval': 0.00401} (T+5360133 ms)
2020-05-07 18:53:56.699 | INFO | Telemetry Process | brokkr.inputs.modbus.ModbusSerialInput | Port details: {'device': '/dev/ttyAMA0', 'name': 'ttyAMA0', 'description': 'ttyAMA0', 'hwid': 'fe201000.serial', 'vid': None, 'pid': None, 'serial_number': None, 'location': None, 'manufacturer': None, 'product': None, 'interface': None, 'usb_device_path': None, 'device_path': '/sys/devices/platform/soc/fe201000.serial', 'subsystem': 'amba', 'usb_interface_path': None} (T+5360133 ms)
2020-05-07 18:54:06.697 | ERROR | Telemetry Process | pymodbus.client.sync | [Errno 13] could not open port /dev/ttyAMA0: [Errno 13] Permission denied: '/dev/ttyAMA0' (T+5370131 ms)
2020-05-07 18:54:06.698 | ERROR | Telemetry Process | brokkr.inputs.modbus.ModbusSerialInput | Error reading modbus data: Cannot connect to device /dev/ttyAMA0 - ttyAMA0 (T+5370132 ms)
2020-05-07 18:54:06.698 | INFO | Telemetry Process | brokkr.inputs.modbus.ModbusSerialInput | Client details: {'method': 'rtu', 'socket': None, 'framer': <pymodbus.framer.rtu_framer.ModbusRtuFramer object at 0xb55a6dd0>, 'transaction': <pymodbus.transaction.DictTransactionManager object at 0xb55a6e90>, '_debug': False, '_debugfd': None, 'broadcast_enable': False, 'port': '/dev/ttyAMA0', 'stopbits': 2, 'bytesize': 8, 'parity': 'N', 'baudrate': 9600, 'timeout': 2, '_strict': False, 'last_frame_end': None, '_t0': 0.0011458333333333333, 'inter_char_timeout': 0.00171875, 'silent_interval': 0.00401} (T+5370132 ms)
2020-05-07 18:54:06.698 | INFO | Telemetry Process | brokkr.inputs.modbus.ModbusSerialInput | Port details: {'device': '/dev/ttyAMA0', 'name': 'ttyAMA0', 'description': 'ttyAMA0', 'hwid': 'fe201000.serial', 'vid': None, 'pid': None, 'serial_number': None, 'location': None, 'manufacturer': None, 'product': None, 'interface': None, 'usb_device_path': None, 'device_path': '/sys/devices/platform/soc/fe201000.serial', 'subsystem': 'amba', 'usb_interface_path': None} (T+5370133 ms)
2020-05-07 18:54:16.697 | ERROR | Telemetry Process | pymodbus.client.sync | [Errno 13] could not open port /dev/ttyAMA0: [Errno 13] Permission denied: '/dev/ttyAMA0' (T+5380131 ms)
2020-05-07 18:54:16.698 | ERROR | Telemetry Process | brokkr.inputs.modbus.ModbusSerialInput | Error reading modbus data: Cannot connect to device /dev/ttyAMA0 - ttyAMA0 (T+5380132 ms)
2020-05-07 18:54:16.698 | INFO | Telemetry Process | brokkr.inputs.modbus.ModbusSerialInput | Client details: {'method': 'rtu', 'socket': None, 'framer': <pymodbus.framer.rtu_framer.ModbusRtuFramer object at 0xb55a6670>, 'transaction': <pymodbus.transaction.DictTransactionManager object at 0xb55a6a30>, '_debug': False, '_debugfd': None, 'broadcast_enable': False, 'port': '/dev/ttyAMA0', 'stopbits': 2, 'bytesize': 8, 'parity': 'N', 'baudrate': 9600, 'timeout': 2, '_strict': False, 'last_frame_end': None, '_t0': 0.0011458333333333333, 'inter_char_timeout': 0.00171875, 'silent_interval': 0.00401} (T+5380133 ms)
2020-05-07 18:54:16.699 | INFO | Telemetry Process | brokkr.inputs.modbus.ModbusSerialInput | Port details: {'device': '/dev/ttyAMA0', 'name': 'ttyAMA0', 'description': 'ttyAMA0', 'hwid': 'fe201000.serial', 'vid': None, 'pid': None, 'serial_number': None, 'location': None, 'manufacturer': None, 'product': None, 'interface': None, 'usb_device_path': None, 'device_path': '/sys/devices/platform/soc/fe201000.serial', 'subsystem': 'amba', 'usb_interface_path': None} (T+5380133 ms)
2020-05-07 18:54:26.697 | ERROR | Telemetry Process | pymodbus.client.sync | [Errno 13] could not open port /dev/ttyAMA0: [Errno 13] Permission denied: '/dev/ttyAMA0' (T+5390131 ms)
2020-05-07 18:54:26.698 | ERROR | Telemetry Process | brokkr.inputs.modbus.ModbusSerialInput | Error reading modbus data: Cannot connect to device /dev/ttyAMA0 - ttyAMA0 (T+5390132 ms)
2020-05-07 18:54:26.699 | INFO | Telemetry Process | brokkr.inputs.modbus.ModbusSerialInput | Client details: {'method': 'rtu', 'socket': None, 'framer': <pymodbus.framer.rtu_framer.ModbusRtuFramer object at 0xb55a6d70>, 'transaction': <pymodbus.transaction.DictTransactionManager object at 0xb55a6f90>, '_debug': False, '_debugfd': None, 'broadcast_enable': False, 'port': '/dev/ttyAMA0', 'stopbits': 2, 'bytesize': 8, 'parity': 'N', 'baudrate': 9600, 'timeout': 2, '_strict': False, 'last_frame_end': None, '_t0': 0.0011458333333333333, 'inter_char_timeout': 0.00171875, 'silent_interval': 0.00401} (T+5390133 ms)
2020-05-07 18:54:26.699 | INFO | Telemetry Process | brokkr.inputs.modbus.ModbusSerialInput | Port details: {'device': '/dev/ttyAMA0', 'name': 'ttyAMA0', 'description': 'ttyAMA0', 'hwid': 'fe201000.serial', 'vid': None, 'pid': None, 'serial_number': None, 'location': None, 'manufacturer': None, 'product': None, 'interface': None, 'usb_device_path': None, 'device_path': '/sys/devices/platform/soc/fe201000.serial', 'subsystem': 'amba', 'usb_interface_path': None} (T+5390133 ms)
2020-05-07 18:54:36.699 | ERROR | Telemetry Process | pymodbus.client.sync | [Errno 13] could not open port /dev/ttyAMA0: [Errno 13] Permission denied: '/dev/ttyAMA0' (T+5400134 ms)
2020-05-07 18:54:36.700 | ERROR | Telemetry Process | brokkr.inputs.modbus.ModbusSerialInput | Error reading modbus data: Cannot connect to device /dev/ttyAMA0 - ttyAMA0 (T+5400135 ms)
2020-05-07 18:54:36.701 | INFO | Telemetry Process | brokkr.inputs.modbus.ModbusSerialInput | Client details: {'method': 'rtu', 'socket': None, 'framer': <pymodbus.framer.rtu_framer.ModbusRtuFramer object at 0xb55a6cf0>, 'transaction': <pymodbus.transaction.DictTransactionManager object at 0xb55a68f0>, '_debug': False, '_debugfd': None, 'broadcast_enable': False, 'port': '/dev/ttyAMA0', 'stopbits': 2, 'bytesize': 8, 'parity': 'N', 'baudrate': 9600, 'timeout': 2, '_strict': False, 'last_frame_end': None, '_t0': 0.0011458333333333333, 'inter_char_timeout': 0.00171875, 'silent_interval': 0.00401} (T+5400135 ms)
2020-05-07 18:54:36.701 | INFO | Telemetry Process | brokkr.inputs.modbus.ModbusSerialInput | Port details: {'device': '/dev/ttyAMA0', 'name': 'ttyAMA0', 'description': 'ttyAMA0', 'hwid': 'fe201000.serial', 'vid': None, 'pid': None, 'serial_number': None, 'location': None, 'manufacturer': None, 'product': None, 'interface': None, 'usb_device_path': None, 'device_path': '/sys/devices/platform/soc/fe201000.serial', 'subsystem': 'amba', 'usb_interface_path': None} (T+5400135 ms)
2020-05-07 18:54:46.689 | ERROR | Telemetry Process | pymodbus.client.sync | [Errno 13] could not open port /dev/ttyAMA0: [Errno 13] Permission denied: '/dev/ttyAMA0' (T+5410123 ms)
2020-05-07 18:54:46.689 | ERROR | Telemetry Process | brokkr.inputs.modbus.ModbusSerialInput | Error reading modbus data: Cannot connect to device /dev/ttyAMA0 - ttyAMA0 (T+5410124 ms)
2020-05-07 18:54:46.689 | INFO | Telemetry Process | brokkr.inputs.modbus.ModbusSerialInput | Client details: {'method': 'rtu', 'socket': None, 'framer': <pymodbus.framer.rtu_framer.ModbusRtuFramer object at 0xb55a6b90>, 'transaction': <pymodbus.transaction.DictTransactionManager object at 0xb55a6930>, '_debug': False, '_debugfd': None, 'broadcast_enable': False, 'port': '/dev/ttyAMA0', 'stopbits': 2, 'bytesize': 8, 'parity': 'N', 'baudrate': 9600, 'timeout': 2, '_strict': False, 'last_frame_end': None, '_t0': 0.0011458333333333333, 'inter_char_timeout': 0.00171875, 'silent_interval': 0.00401} (T+5410124 ms)
2020-05-07 18:54:46.690 | INFO | Telemetry Process | brokkr.inputs.modbus.ModbusSerialInput | Port details: {'device': '/dev/ttyAMA0', 'name': 'ttyAMA0', 'description': 'ttyAMA0', 'hwid': 'fe201000.serial', 'vid': None, 'pid': None, 'serial_number': None, 'location': None, 'manufacturer': None, 'product': None, 'interface': None, 'usb_device_path': None, 'device_path': '/sys/devices/platform/soc/fe201000.serial', 'subsystem': 'amba', 'usb_interface_path': None} (T+5410124 ms)
