    parity=self.parity)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 286, in open
    self._update_dtr_state()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 634, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
OSError: [Errno 5] Input/output error
2020-01-13 12:54:07.213 | 2227200131 | CRITICAL | brokkr.monitor | OSError caught at main level: [Errno 5] Input/output error
2020-01-13 12:54:07.215 | 2227200132 | INFO | brokkr.monitor | Details:
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 75, in start_monitoring
    record_status_data(output_path, verbose=verbose)
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 49, in record_status_data
    status_data = get_status_data()
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 39, in get_status_data
    output_data = item.fn()
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 244, in get_sunsaver_data
    register_data = read_raw_sunsaver_data(**kwargs)
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 160, in read_raw_sunsaver_data
    if mppt_client.connect():
  File "/home/thor/dev/brokkrenv/lib/python3.7/site-packages/pymodbus/client/sync.py", line 481, in connect
    parity=self.parity)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 286, in open
    self._update_dtr_state()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 634, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
OSError: [Errno 5] Input/output error
