2019-10-29 11:36:41.817 | 33 | INFO | brokkr.startup | Starting Brokkr...
2019-10-29 11:36:44.950 | 3166 | ERROR | brokkr.sunsaver | ModbusIOException reading register data for /dev/ttyUSB0: Modbus Error: [Input/Output] Modbus Error: [Invalid Message] Incomplete message received, expected at least 2 bytes (0 received)
2019-10-29 11:36:44.962 | 3178 | INFO | brokkr.sunsaver | Details: ModbusSerialClient(rtu baud[9600])
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 164, in read_raw_sunsaver_data
    raise register_data
pymodbus.exceptions.ModbusIOException: Modbus Error: [Input/Output] Modbus Error: [Invalid Message] Incomplete message received, expected at least 2 bytes (0 received)
2019-10-29 11:36:54.867 | 13083 | ERROR | brokkr.sunsaver | ModbusIOException reading register data for /dev/ttyUSB0: Modbus Error: [Input/Output] Modbus Error: [Invalid Message] Incomplete message received, expected at least 2 bytes (0 received)
2019-10-29 11:36:54.884 | 13100 | INFO | brokkr.sunsaver | Details: ModbusSerialClient(rtu baud[9600])
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 164, in read_raw_sunsaver_data
    raise register_data
pymodbus.exceptions.ModbusIOException: Modbus Error: [Input/Output] Modbus Error: [Invalid Message] Incomplete message received, expected at least 2 bytes (0 received)
2019-10-29 11:36:59.205 | 17421 | INFO | brokkr.startup | Interrupted by signal 2; terminating Brokkr
2019-10-29 11:40:16.784 | 31 | INFO | brokkr.startup | Starting Brokkr...
2019-10-29 11:40:19.874 | 3121 | ERROR | brokkr.sunsaver | ModbusIOException reading register data for /dev/ttyUSB0: Modbus Error: [Input/Output] Modbus Error: [Invalid Message] Incomplete message received, expected at least 2 bytes (0 received)
2019-10-29 11:40:19.896 | 3143 | INFO | brokkr.sunsaver | Details: ModbusSerialClient(rtu baud[9600])
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 164, in read_raw_sunsaver_data
    raise register_data
pymodbus.exceptions.ModbusIOException: Modbus Error: [Input/Output] Modbus Error: [Invalid Message] Incomplete message received, expected at least 2 bytes (0 received)
2019-10-29 11:40:29.835 | 13082 | ERROR | brokkr.sunsaver | ModbusIOException reading register data for /dev/ttyUSB0: Modbus Error: [Input/Output] Modbus Error: [Invalid Message] Incomplete message received, expected at least 2 bytes (0 received)
2019-10-29 11:40:29.861 | 13108 | INFO | brokkr.sunsaver | Details: ModbusSerialClient(rtu baud[9600])
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 164, in read_raw_sunsaver_data
    raise register_data
pymodbus.exceptions.ModbusIOException: Modbus Error: [Input/Output] Modbus Error: [Invalid Message] Incomplete message received, expected at least 2 bytes (0 received)
2019-10-29 11:40:33.617 | 16864 | INFO | brokkr.startup | Interrupted by signal 2; terminating Brokkr
2019-10-29 11:45:18.161 | 31 | INFO | brokkr.startup | Starting Brokkr...
2019-10-29 11:45:21.248 | 3118 | ERROR | brokkr.sunsaver | ModbusIOException reading register data for /dev/ttyUSB0: Modbus Error: [Input/Output] Modbus Error: [Invalid Message] Incomplete message received, expected at least 2 bytes (0 received)
2019-10-29 11:45:21.260 | 3131 | INFO | brokkr.sunsaver | Details: ModbusSerialClient(rtu baud[9600])
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 164, in read_raw_sunsaver_data
    raise register_data
pymodbus.exceptions.ModbusIOException: Modbus Error: [Input/Output] Modbus Error: [Invalid Message] Incomplete message received, expected at least 2 bytes (0 received)
2019-10-29 11:45:25.312 | 7183 | INFO | brokkr.startup | Interrupted by signal 2; terminating Brokkr
2019-10-29 13:05:25.222 | 74 | INFO | brokkr.startup | Starting Brokkr...
2019-10-29 13:05:28.407 | 3258 | ERROR | brokkr.sunsaver | ModbusIOException reading register data for /dev/ttyUSB0: Modbus Error: [Input/Output] Modbus Error: [Invalid Message] Incomplete message received, expected at least 2 bytes (0 received)
2019-10-29 13:05:28.408 | 3260 | INFO | brokkr.sunsaver | Details: ModbusSerialClient(rtu baud[9600])
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 164, in read_raw_sunsaver_data
    raise register_data
pymodbus.exceptions.ModbusIOException: Modbus Error: [Input/Output] Modbus Error: [Invalid Message] Incomplete message received, expected at least 2 bytes (0 received)
2019-10-29 13:09:49.165 | 264016 | INFO | brokkr.startup | Interrupted by signal 15; terminating Brokkr
2019-10-29 13:11:24.368 | 86 | INFO | brokkr.startup | Starting Brokkr...
2019-10-29 13:59:01.118 | 2856837 | INFO | brokkr.startup | Interrupted by signal 15; terminating Brokkr
2019-10-29 14:47:29.310 | 88 | INFO | brokkr.startup | Starting Brokkr...
2019-11-03 02:53:47.271 | 389178049 | INFO | brokkr.startup | Interrupted by signal 15; terminating Brokkr
2019-11-03 02:54:21.720 | 91 | INFO | brokkr.startup | Starting Brokkr...
2019-11-07 05:01:43.577 | 353241949 | INFO | brokkr.startup | Interrupted by signal 15; terminating Brokkr
2019-11-07 05:15:26.938 | 92 | INFO | brokkr.startup | Starting Brokkr...
2019-11-07 05:39:56.923 | 1470077 | INFO | brokkr.startup | Interrupted by signal 15; terminating Brokkr
2019-11-07 07:40:29.802 | 43 | INFO | brokkr.startup | Starting Brokkr...
2019-11-16 00:55:32.862 | 753303104 | ERROR | brokkr.sunsaver | ModbusIOException reading register data for /dev/ttyUSB0: Modbus Error: [Input/Output] No Response received from the remote unit/Unable to decode response
2019-11-16 00:55:32.863 | 753303105 | INFO | brokkr.sunsaver | Details: ModbusSerialClient(rtu baud[9600])
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 164, in read_raw_sunsaver_data
    raise register_data
pymodbus.exceptions.ModbusIOException: Modbus Error: [Input/Output] No Response received from the remote unit/Unable to decode response
2019-11-19 11:32:47.311 | 1050737553 | INFO | brokkr.startup | Interrupted by signal 15; terminating Brokkr
2019-11-19 11:34:02.913 | 46 | INFO | brokkr.startup | Starting Brokkr...
2019-12-01 01:09:43.238 | 109 | INFO | brokkr.startup | Starting Brokkr...
2019-12-12 02:51:50.663 | 956527534 | INFO | brokkr.startup | Interrupted by signal 15; terminating Brokkr
2019-12-12 02:52:24.130 | 105 | INFO | brokkr.startup | Starting Brokkr...
2019-12-18 17:44:28.175 | 571924150 | ERROR | brokkr.sunsaver | ModbusIOException reading register data for /dev/ttyUSB0: Modbus Error: [Input/Output] Modbus Error: [Invalid Message] Incomplete message received, expected at least 2 bytes (0 received)
2019-12-18 17:44:28.179 | 571924155 | INFO | brokkr.sunsaver | Details: ModbusSerialClient(rtu baud[9600])
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 165, in read_raw_sunsaver_data
    raise register_data
pymodbus.exceptions.ModbusIOException: Modbus Error: [Input/Output] Modbus Error: [Invalid Message] Incomplete message received, expected at least 2 bytes (0 received)
2019-12-18 17:45:28.166 | 571984142 | ERROR | brokkr.sunsaver | ModbusIOException reading register data for /dev/ttyUSB0: Modbus Error: [Input/Output] Modbus Error: [Invalid Message] Incomplete message received, expected at least 2 bytes (0 received)
2019-12-18 17:45:28.171 | 571984146 | INFO | brokkr.sunsaver | Details: ModbusSerialClient(rtu baud[9600])
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 165, in read_raw_sunsaver_data
    raise register_data
pymodbus.exceptions.ModbusIOException: Modbus Error: [Input/Output] Modbus Error: [Invalid Message] Incomplete message received, expected at least 2 bytes (0 received)
2019-12-18 17:46:28.170 | 572044145 | ERROR | brokkr.sunsaver | ModbusIOException reading register data for /dev/ttyUSB0: Modbus Error: [Input/Output] Modbus Error: [Invalid Message] Incomplete message received, expected at least 2 bytes (0 received)
2019-12-18 17:46:28.170 | 572044146 | INFO | brokkr.sunsaver | Details: ModbusSerialClient(rtu baud[9600])
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 165, in read_raw_sunsaver_data
    raise register_data
pymodbus.exceptions.ModbusIOException: Modbus Error: [Input/Output] Modbus Error: [Invalid Message] Incomplete message received, expected at least 2 bytes (0 received)
2019-12-18 17:47:28.167 | 572104143 | ERROR | brokkr.sunsaver | ModbusIOException reading register data for /dev/ttyUSB0: Modbus Error: [Input/Output] Modbus Error: [Invalid Message] Incomplete message received, expected at least 2 bytes (0 received)
2019-12-18 17:47:28.172 | 572104147 | INFO | brokkr.sunsaver | Details: ModbusSerialClient(rtu baud[9600])
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 165, in read_raw_sunsaver_data
    raise register_data
pymodbus.exceptions.ModbusIOException: Modbus Error: [Input/Output] Modbus Error: [Invalid Message] Incomplete message received, expected at least 2 bytes (0 received)
2019-12-18 17:48:28.167 | 572164142 | ERROR | brokkr.sunsaver | ModbusIOException reading register data for /dev/ttyUSB0: Modbus Error: [Input/Output] Modbus Error: [Invalid Message] Incomplete message received, expected at least 2 bytes (0 received)
2019-12-18 17:48:28.171 | 572164146 | INFO | brokkr.sunsaver | Details: ModbusSerialClient(rtu baud[9600])
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 165, in read_raw_sunsaver_data
    raise register_data
pymodbus.exceptions.ModbusIOException: Modbus Error: [Input/Output] Modbus Error: [Invalid Message] Incomplete message received, expected at least 2 bytes (0 received)
2019-12-18 17:49:28.166 | 572224142 | ERROR | brokkr.sunsaver | ModbusIOException reading register data for /dev/ttyUSB0: Modbus Error: [Input/Output] Modbus Error: [Invalid Message] Incomplete message received, expected at least 2 bytes (0 received)
2019-12-18 17:49:28.171 | 572224146 | INFO | brokkr.sunsaver | Details: ModbusSerialClient(rtu baud[9600])
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 165, in read_raw_sunsaver_data
    raise register_data
pymodbus.exceptions.ModbusIOException: Modbus Error: [Input/Output] Modbus Error: [Invalid Message] Incomplete message received, expected at least 2 bytes (0 received)
2019-12-18 17:50:27.168 | 572283143 | ERROR | brokkr.sunsaver | ModbusIOException reading register data for /dev/ttyUSB0: Modbus Error: [Input/Output] Modbus Error: [Invalid Message] Incomplete message received, expected at least 2 bytes (0 received)
2019-12-18 17:50:27.169 | 572283144 | INFO | brokkr.sunsaver | Details: ModbusSerialClient(rtu baud[9600])
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 165, in read_raw_sunsaver_data
    raise register_data
pymodbus.exceptions.ModbusIOException: Modbus Error: [Input/Output] Modbus Error: [Invalid Message] Incomplete message received, expected at least 2 bytes (0 received)
2019-12-18 17:51:28.166 | 572344142 | ERROR | brokkr.sunsaver | ModbusIOException reading register data for /dev/ttyUSB0: Modbus Error: [Input/Output] Modbus Error: [Invalid Message] Incomplete message received, expected at least 2 bytes (0 received)
2019-12-18 17:51:28.168 | 572344143 | INFO | brokkr.sunsaver | Details: ModbusSerialClient(rtu baud[9600])
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 165, in read_raw_sunsaver_data
    raise register_data
pymodbus.exceptions.ModbusIOException: Modbus Error: [Input/Output] Modbus Error: [Invalid Message] Incomplete message received, expected at least 2 bytes (0 received)
2019-12-18 17:52:28.167 | 572404142 | ERROR | brokkr.sunsaver | ModbusIOException reading register data for /dev/ttyUSB0: Modbus Error: [Input/Output] Modbus Error: [Invalid Message] Incomplete message received, expected at least 2 bytes (0 received)
2019-12-18 17:52:28.168 | 572404143 | INFO | brokkr.sunsaver | Details: ModbusS2019-12-18 18:14:07.194 | 111 | INFO | brokkr.startup | Starting Brokkr...
2020-01-12 02:17:08.224 | 2102581142 | CRITICAL | brokkr.monitor | OSError caught at main level: [Errno 5] Input/output error
2020-01-12 02:17:08.225 | 2102581143 | INFO | brokkr.monitor | Details:
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 75, in start_monitoring
    record_status_data(output_path, verbose=verbose)
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 49, in record_status_data
    status_data = get_status_data()
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 39, in get_status_data
    output_data = item.fn()
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 244, in get_sunsaver_data
    register_data = read_raw_sunsaver_data(**kwargs)
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 160, in read_raw_sunsaver_data
    if mppt_client.connect():
  File "/home/thor/dev/brokkrenv/lib/python3.7/site-packages/pymodbus/client/sync.py", line 481, in connect
    parity=self.parity)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 286, in open
    self._update_dtr_state()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 634, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
OSError: [Errno 5] Input/output error
2020-01-12 02:18:08.221 | 2102641139 | CRITICAL | brokkr.monitor | OSError caught at main level: [Errno 5] Input/output error
2020-01-12 02:18:08.223 | 2102641141 | INFO | brokkr.monitor | Details:
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 75, in start_monitoring
    record_status_data(output_path, verbose=verbose)
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 49, in record_status_data
    status_data = get_status_data()
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 39, in get_status_data
    output_data = item.fn()
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 244, in get_sunsaver_data
    register_data = read_raw_sunsaver_data(**kwargs)
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 160, in read_raw_sunsaver_data
    if mppt_client.connect():
  File "/home/thor/dev/brokkrenv/lib/python3.7/site-packages/pymodbus/client/sync.py", line 481, in connect
    parity=self.parity)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 286, in open
    self._update_dtr_state()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 634, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
OSError: [Errno 5] Input/output error
2020-01-12 02:19:08.221 | 2102701139 | CRITICAL | brokkr.monitor | OSError caught at main level: [Errno 5] Input/output error
2020-01-12 02:19:08.223 | 2102701140 | INFO | brokkr.monitor | Details:
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 75, in start_monitoring
    record_status_data(output_path, verbose=verbose)
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 49, in record_status_data
    status_data = get_status_data()
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 39, in get_status_data
    output_data = item.fn()
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 244, in get_sunsaver_data
    register_data = read_raw_sunsaver_data(**kwargs)
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 160, in read_raw_sunsaver_data
    if mppt_client.connect():
  File "/home/thor/dev/brokkrenv/lib/python3.7/site-packages/pymodbus/client/sync.py", line 481, in connect
    parity=self.parity)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 286, in open
    self._update_dtr_state()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 634, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
OSError: [Errno 5] Input/output error
2020-01-12 02:20:08.221 | 2102761139 | CRITICAL | brokkr.monitor | OSError caught at main level: [Errno 5] Input/output error
2020-01-12 02:20:08.223 | 2102761141 | INFO | brokkr.monitor | Details:
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 75, in start_monitoring
    record_status_data(output_path, verbose=verbose)
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 49, in record_status_data
    status_data = get_status_data()
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 39, in get_status_data
    output_data = item.fn()
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 244, in get_sunsaver_data
    register_data = read_raw_sunsaver_data(**kwargs)
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 160, in read_raw_sunsaver_data
    if mppt_client.connect():
  File "/home/thor/dev/brokkrenv/lib/python3.7/site-packages/pymodbus/client/sync.py", line 481, in connect
    parity=self.parity)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 286, in open
    self._update_dtr_state()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 634, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
OSError: [Errno 5] Input/output error
2020-01-12 02:21:08.221 | 2102821139 | CRITICAL | brokkr.monitor | OSError caught at main level: [Errno 5] Input/output error
2020-01-12 02:21:08.223 | 2102821140 | INFO | brokkr.monitor | Details:
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 75, in start_monitoring
    record_status_data(output_path, verbose=verbose)
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 49, in record_status_data
    status_data = get_status_data()
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 39, in get_status_data
    output_data = item.fn()
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 244, in get_sunsaver_data
    register_data = read_raw_sunsaver_data(**kwargs)
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 160, in read_raw_sunsaver_data
    if mppt_client.connect():
  File "/home/thor/dev/brokkrenv/lib/python3.7/site-packages/pymodbus/client/sync.py", line 481, in connect
    parity=self.parity)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 286, in open
    self._update_dtr_state()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 634, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
OSError: [Errno 5] Input/output error
2020-01-12 02:22:08.221 | 2102881139 | CRITICAL | brokkr.monitor | OSError caught at main level: [Errno 5] Input/output error
2020-01-12 02:22:08.223 | 2102881141 | INFO | brokkr.monitor | Details:
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 75, in start_monitoring
    record_status_data(output_path, verbose=verbose)
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 49, in record_status_data
    status_data = get_status_data()
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 39, in get_status_data
    output_data = item.fn()
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 244, in get_sunsaver_data
    register_data = read_raw_sunsaver_data(**kwargs)
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 160, in read_raw_sunsaver_data
    if mppt_client.connect():
  File "/home/thor/dev/brokkrenv/lib/python3.7/site-packages/pymodbus/client/sync.py", line 481, in connect
    parity=self.parity)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 286, in open
    self._update_dtr_state()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 634, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
OSError: [Errno 5] Input/output error
2020-01-12 02:23:08.223 | 2102941141 | CRITICAL | brokkr.monitor | OSError caught at main level: [Errno 5] Input/output error
2020-01-12 02:23:08.224 | 2102941142 | INFO | brokkr.monitor | Details:
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 75, in start_monitoring
    record_status_data(output_path, verbose=verbose)
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 49, in record_status_data
    status_data = get_status_data()
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 39, in get_status_data
    output_data = item.fn()
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 244, in get_sunsaver_data
    register_data = read_raw_sunsaver_data(**kwargs)
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 160, in read_raw_sunsaver_data
    if mppt_client.connect():
  File "/home/thor/dev/brokkrenv/lib/python3.7/site-packages/pymodbus/client/sync.py", line 481, in connect
    parity=self.parity)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 286, in open
    self._update_dtr_state()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 634, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
OSError: [Errno 5] Input/output error
2020-01-12 02:24:08.211 | 2103001129 | CRITICAL | brokkr.monitor | OSError caught at main level: [Errno 5] Input/output error
2020-01-12 02:24:08.212 | 2103001129 | INFO | brokkr.monitor | Details:
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 75, in start_monitoring
    record_status_data(output_path, verbose=verbose)
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 49, in record_status_data
    status_data = get_status_data()
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 39, in get_status_data
    output_data = item.fn()
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 244, in get_sunsaver_data
    register_data = read_raw_sunsaver_data(**kwargs)
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 160, in read_raw_sunsaver_data
    if mppt_client.connect():
  File "/home/thor/dev/brokkrenv/lib/python3.7/site-packages/pymodbus/client/sync.py", line 481, in connect
    parity=self.parity)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 286, in open
    self._update_dtr_state()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 634, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
OSError: [Errno 5] Input/output error
2020-01-12 02:25:08.214 | 2103061131 | CRITICAL | brokkr.monitor | OSError caught at main level: [Errno 5] Input/output error
2020-01-12 02:25:08.214 | 2103061132 | INFO | brokkr.monitor | Details:
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 75, in start_monitoring
    record_status_data(output_path, verbose=verbose)
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 49, in record_status_data
    status_data = get_status_data()
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 39, in get_status_data
    output_data = item.fn()
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 244, in get_sunsaver_data
    register_data = read_raw_sunsaver_data(**kwargs)
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 160, in read_raw_sunsaver_data
    if mppt_client.connect():
  File "/home/thor/dev/brokkrenv/lib/python3.7/site-packages/pymodbus/client/sync.py", line 481, in connect
    parity=self.parity)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 286, in open
    self._update_dtr_state()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 634, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
OSError: [Errno 5] Input/output error
2020-01-12 02:26:08.221 | 2103121139 | CRITICAL | brokkr.monitor | OSError caught at main level: [Errno 5] Input/output error
2020-01-12 02:26:08.223 | 2103121140 | INFO | brokkr.monitor | Details:
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 75, in start_monitoring
    record_status_data(output_path, verbose=verbose)
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 49, in record_status_data
    status_data = get_status_data()
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 39, in get_status_data
    output_data = item.fn()
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 244, in get_sunsaver_data
    register_data = read_raw_sunsaver_data(**kwargs)
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 160, in read_raw_sunsaver_data
    if mppt_client.connect():
  File "/home/thor/dev/brokkrenv/lib/python3.7/site-packages/pymodbus/client/sync.py", line 481, in connect
    parity=self.parity)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 286, in open
    self._update_dtr_state()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 634, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
OSError: [Errno 5] Input/output error
2020-01-12 02:27:08.221 | 2103181139 | CRITICAL | brokkr.monitor | OSError caught at main level: [Errno 5] Input/output error
2020-01-12 02:27:08.222 | 2103181140 | INFO | brokkr.monitor | Details:
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 75, in start_monitoring
    record_status_data(output_path, verbose=verbose)
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 49, in record_status_data
    status_data = get_status_data()
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 39, in get_status_data
    output_data = item.fn()
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 244, in get_sunsaver_data
    register_data = read_raw_sunsaver_data(**kwargs)
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 160, in read_raw_sunsaver_data
    if mppt_client.connect():
  File "/home/thor/dev/brokkrenv/lib/python3.7/site-packages/pymodbus/client/sync.py", line 481, in connect
    parity=self.parity)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 286, in open
    self._update_dtr_state()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 634, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
OSError: [Errno 5] Input/output error
2020-01-12 02:28:08.221 | 2103241139 | CRITICAL | brokkr.monitor | OSError caught at main level: [Errno 5] Input/output error
2020-01-12 02:28:08.223 | 2103241141 | INFO | brokkr.monitor | Details:
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 75, in start_monitoring
    record_status_data(output_path, verbose=verbose)
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 49, in record_status_data
    status_data = get_status_data()
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 39, in get_status_data
    output_data = item.fn()
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 244, in get_sunsaver_data
    register_data = read_raw_sunsaver_data(**kwargs)
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 160, in read_raw_sunsaver_data
    if mppt_client.connect():
  File "/home/thor/dev/brokkrenv/lib/python3.7/site-packages/pymodbus/client/sync.py", line 481, in connect
    parity=self.parity)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 286, in open
    self._update_dtr_state()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 634, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
OSError: [Errno 5] Input/output error
2020-01-12 02:29:08.221 | 2103301139 | CRITICAL | brokkr.monitor | OSError caught at main level: [Errno 5] Input/output error
2020-01-12 02:29:08.223 | 2103301140 | INFO | brokkr.monitor | Details:
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 75, in start_monitoring
    record_status_data(output_path, verbose=verbose)
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 49, in record_status_data
    status_data = get_status_data()
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 39, in get_status_data
    output_data = item.fn()
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 244, in get_sunsaver_data
    register_data = read_raw_sunsaver_data(**kwargs)
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 160, in read_raw_sunsaver_data
    if mppt_client.connect():
  File "/home/thor/dev/brokkrenv/lib/python3.7/site-packages/pymodbus/client/sync.py", line 481, in connect
    parity=self.parity)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 286, in open
    self._update_dtr_state()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 634, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
OSError: [Errno 5] Input/output error
2020-01-12 02:30:08.222 | 2103361140 | CRITICAL | brokkr.monitor | OSError caught at main level: [Errno 5] Input/output error
2020-01-12 02:30:08.224 | 2103361142 | INFO | brokkr.monitor | Details:
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 75, in start_monitoring
    record_status_data(output_path, verbose=verbose)
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 49, in record_status_data
    status_data = get_status_data()
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 39, in get_status_data
    output_data = item.fn()
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 244, in get_sunsaver_data
    register_data = read_raw_sunsaver_data(**kwargs)
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 160, in read_raw_sunsaver_data
    if mppt_client.connect():
  File "/home/thor/dev/brokkrenv/lib/python3.7/site-packages/pymodbus/client/sync.py", line 481, in connect
    parity=self.parity)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 286, in open
    self._update_dtr_state()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 634, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
OSError: [Errno 5] Input/output error
2020-01-12 02:31:08.221 | 2103421139 | CRITICAL | brokkr.monitor | OSError caught at main level: [Errno 5] Input/output error
2020-01-12 02:31:08.223 | 2103421141 | INFO | brokkr.monitor | Details:
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 75, in start_monitoring
    record_status_data(output_path, verbose=verbose)
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 49, in record_status_data
    status_data = get_status_data()
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 39, in get_status_data
    output_data = item.fn()
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 244, in get_sunsaver_data
    register_data = read_raw_sunsaver_data(**kwargs)
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 160, in read_raw_sunsaver_data
    if mppt_client.connect():
  File "/home/thor/dev/brokkrenv/lib/python3.7/site-packages/pymodbus/client/sync.py", line 481, in connect
    parity=self.parity)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 286, in open
    self._update_dtr_state()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 634, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
OSError: [Errno 5] Input/output error
2020-01-12 02:32:08.222 | 2103481140 | CRITICAL | brokkr.monitor | OSError caught at main level: [Errno 5] Input/output error
2020-01-12 02:32:08.224 | 2103481141 | INFO | brokkr.monitor | Details:
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 75, in start_monitoring
    record_status_data(output_path, verbose=verbose)
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 49, in record_status_data
    status_data = get_status_data()
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 39, in get_status_data
    output_data = item.fn()
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 244, in get_sunsaver_data
    register_data = read_raw_sunsaver_data(**kwargs)
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 160, in read_raw_sunsaver_data
    if mppt_client.connect():
  File "/home/thor/dev/brokkrenv/lib/python3.7/site-packages/pymodbus/client/sync.py", line 481, in connect
    parity=self.parity)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 286, in open
    self._update_dtr_state()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 634, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
OSError: [Errno 5] Input/output error
2020-01-12 02:33:08.221 | 2103541139 | CRITICAL | brokkr.monitor | OSError caught at main level: [Errno 5] Input/output error
2020-01-12 02:33:08.223 | 2103541141 | INFO | brokkr.monitor | Details:
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 75, in start_monitoring
    record_status_data(output_path, verbose=verbose)
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 49, in record_status_data
    status_data = get_status_data()
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 39, in get_status_data
    output_data = item.fn()
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 244, in get_sunsaver_data
    register_data = read_raw_sunsaver_data(**kwargs)
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 160, in read_raw_sunsaver_data
    if mppt_client.connect():
  File "/home/thor/dev/brokkrenv/lib/python3.7/site-packages/pymodbus/client/sync.py", line 481, in connect
    parity=self.parity)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 286, in open
    self._update_dtr_state()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 634, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
OSError: [Errno 5] Input/output error
2020-01-12 02:34:08.211 | 2103601128 | CRITICAL | brokkr.monitor | OSError caught at main level: [Errno 5] Input/output error
2020-01-12 02:34:08.211 | 2103601129 | INFO | brokkr.monitor | Details:
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 75, in start_monitoring
    record_status_data(output_path, verbose=verbose)
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 49, in record_status_data
    status_data = get_status_data()
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 39, in get_status_data
    output_data = item.fn()
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 244, in get_sunsaver_data
    register_data = read_raw_sunsaver_data(**kwargs)
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 160, in read_raw_sunsaver_data
    if mppt_client.connect():
  File "/home/thor/dev/brokkrenv/lib/python3.7/site-packages/pymodbus/client/sync.py", line 481, in connect
    parity=self.parity)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 286, in open
    self._update_dtr_state()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 634, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
OSError: [Errno 5] Input/output error
2020-01-12 02:35:08.221 | 2103661139 | CRITICAL | brokkr.monitor | OSError caught at main level: [Errno 5] Input/output error
2020-01-12 02:35:08.223 | 2103661141 | INFO | brokkr.monitor | Details:
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 75, in start_monitoring
    record_status_data(output_path, verbose=verbose)
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 49, in record_status_data
    status_data = get_status_data()
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 39, in get_status_data
    output_data = item.fn()
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 244, in get_sunsaver_data
    register_data = read_raw_sunsaver_data(**kwargs)
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 160, in read_raw_sunsaver_data
    if mppt_client.connect():
  File "/home/thor/dev/brokkrenv/lib/python3.7/site-packages/pymodbus/client/sync.py", line 481, in connect
    parity=self.parity)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 286, in open
    self._update_dtr_state()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 634, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
OSError: [Errno 5] Input/output error
2020-01-12 02:36:08.221 | 2103721139 | CRITICAL | brokkr.monitor | OSError caught at main level: [Errno 5] Input/output error
2020-01-12 02:36:08.223 | 2103721141 | INFO | brokkr.monitor | Details:
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 75, in start_monitoring
    record_status_data(output_path, verbose=verbose)
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 49, in record_status_data
    status_data = get_status_data()
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 39, in get_status_data
    output_data = item.fn()
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 244, in get_sunsaver_data
    register_data = read_raw_sunsaver_data(**kwargs)
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 160, in read_raw_sunsaver_data
    if mppt_client.connect():
  File "/home/thor/dev/brokkrenv/lib/python3.7/site-packages/pymodbus/client/sync.py", line 481, in connect
    parity=self.parity)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 286, in open
    self._update_dtr_state()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 634, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
OSError: [Errno 5] Input/output error
2020-01-12 02:37:08.221 | 2103781139 | CRITICAL | brokkr.monitor | OSError caught at main level: [Errno 5] Input/output error
2020-01-12 02:37:08.223 | 2103781141 | INFO | brokkr.monitor | Details:
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 75, in start_monitoring
    record_status_data(output_path, verbose=verbose)
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 49, in record_status_data
    status_data = get_status_data()
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 39, in get_status_data
    output_data = item.fn()
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 244, in get_sunsaver_data
    register_data = read_raw_sunsaver_data(**kwargs)
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 160, in read_raw_sunsaver_data
    if mppt_client.connect():
  File "/home/thor/dev/brokkrenv/lib/python3.7/site-packages/pymodbus/client/sync.py", line 481, in connect
    parity=self.parity)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 286, in open
    self._update_dtr_state()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 634, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
OSError: [Errno 5] Input/output error
2020-01-12 02:38:08.221 | 2103841139 | CRITICAL | brokkr.monitor | OSError caught at main level: [Errno 5] Input/output error
2020-01-12 02:38:08.223 | 2103841141 | INFO | brokkr.monitor | Details:
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 75, in start_monitoring
    record_status_data(output_path, verbose=verbose)
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 49, in record_status_data
    status_data = get_status_data()
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 39, in get_status_data
    output_data = item.fn()
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 244, in get_sunsaver_data
    register_data = read_raw_sunsaver_data(**kwargs)
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 160, in read_raw_sunsaver_data
    if mppt_client.connect():
  File "/home/thor/dev/brokkrenv/lib/python3.7/site-packages/pymodbus/client/sync.py", line 481, in connect
    parity=self.parity)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 286, in open
    self._update_dtr_state()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 634, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
OSError: [Errno 5] Input/output error
2020-01-12 02:39:08.221 | 2103901139 | CRITICAL | brokkr.monitor | OSError caught at main level: [Errno 5] Input/output error
2020-01-12 02:39:08.223 | 2103901141 | INFO | brokkr.monitor | Details:
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 75, in start_monitoring
    record_status_data(output_path, verbose=verbose)
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 49, in record_status_data
    status_data = get_status_data()
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 39, in get_status_data
    output_data = item.fn()
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 244, in get_sunsaver_data
    register_data = read_raw_sunsaver_data(**kwargs)
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 160, in read_raw_sunsaver_data
    if mppt_client.connect():
  File "/home/thor/dev/brokkrenv/lib/python3.7/site-packages/pymodbus/client/sync.py", line 481, in connect
    parity=self.parity)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 286, in open
    self._update_dtr_state()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 634, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
OSError: [Errno 5] Input/output error
2020-01-12 02:40:08.222 | 2103961140 | CRITICAL | brokkr.monitor | OSError caught at main level: [Errno 5] Input/output error
2020-01-12 02:40:08.224 | 2103961141 | INFO | brokkr.monitor | Details:
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 75, in start_monitoring
    record_status_data(output_path, verbose=verbose)
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 49, in record_status_data
    status_data = get_status_data()
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 39, in get_status_data
    output_data = item.fn()
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 244, in get_sunsaver_data
    register_data = read_raw_sunsaver_data(**kwargs)
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 160, in read_raw_sunsaver_data
    if mppt_client.connect():
  File "/home/thor/dev/brokkrenv/lib/python3.7/site-packages/pymodbus/client/sync.py", line 481, in connect
    parity=self.parity)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 286, in open
    self._update_dtr_state()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 634, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
OSError: [Errno 5] Input/output error
2020-01-12 02:41:08.221 | 2104021139 | CRITICAL | brokkr.monitor | OSError caught at main level: [Errno 5] Input/output error
2020-01-12 02:41:08.223 | 2104021141 | INFO | brokkr.monitor | Details:
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 75, in start_monitoring
    record_status_data(output_path, verbose=verbose)
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 49, in record_status_data
    status_data = get_status_data()
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 39, in get_status_data
    output_data = item.fn()
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 244, in get_sunsaver_data
    register_data = read_raw_sunsaver_data(**kwargs)
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 160, in read_raw_sunsaver_data
    if mppt_client.connect():
  File "/home/thor/dev/brokkrenv/lib/python3.7/site-packages/pymodbus/client/sync.py", line 481, in connect
    parity=self.parity)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 286, in open
    self._update_dtr_state()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 634, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
OSError: [Errno 5] Input/output error
2020-01-12 02:42:08.221 | 2104081139 | CRITICAL | brokkr.monitor | OSError caught at main level: [Errno 5] Input/output error
2020-01-12 02:42:08.223 | 2104081141 | INFO | brokkr.monitor | Details:
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 75, in start_monitoring
    record_status_data(output_path, verbose=verbose)
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 49, in record_status_data
    status_data = get_status_data()
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 39, in get_status_data
    output_data = item.fn()
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 244, in get_sunsaver_data
    register_data = read_raw_sunsaver_data(**kwargs)
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 160, in read_raw_sunsaver_data
    if mppt_client.connect():
  File "/home/thor/dev/brokkrenv/lib/python3.7/site-packages/pymodbus/client/sync.py", line 481, in connect
    parity=self.parity)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 286, in open
    self._update_dtr_state()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 634, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
OSError: [Errno 5] Input/output error
2020-01-12 02:43:08.221 | 2104141139 | CRITICAL | brokkr.monitor | OSError caught at main level: [Errno 5] Input/output error
2020-01-12 02:43:08.223 | 2104141141 | INFO | brokkr.monitor | Details:
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 75, in start_monitoring
    record_status_data(output_path, verbose=verbose)
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 49, in record_status_data
    status_data = get_status_data()
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 39, in get_status_data
    output_data = item.fn()
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 244, in get_sunsaver_data
    register_data = read_raw_sunsaver_data(**kwargs)
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 160, in read_raw_sunsaver_data
    if mppt_client.connect():
  File "/home/thor/dev/brokkrenv/lib/python3.7/site-packages/pymodbus/client/sync.py", line 481, in connect
    parity=self.parity)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 286, in open
    self._update_dtr_state()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 634, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
OSError: [Errno 5] Input/output error
2020-01-12 02:44:08.211 | 2104201128 | CRITICAL | brokkr.monitor | OSError caught at main level: [Errno 5] Input/output error
2020-01-12 02:44:08.211 | 2104201129 | INFO | brokkr.monitor | Details:
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 75, in start_monitoring
    record_status_data(output_path, verbose=verbose)
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 49, in record_status_data
    status_data = get_status_data()
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 39, in get_status_data
    output_data = item.fn()
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 244, in get_sunsaver_data
    register_data = read_raw_sunsaver_data(**kwargs)
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 160, in read_raw_sunsaver_data
    if mppt_client.connect():
  File "/home/thor/dev/brokkrenv/lib/python3.7/site-packages/pymodbus/client/sync.py", line 481, in connect
    parity=self.parity)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 286, in open
    self._update_dtr_state()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 634, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
OSError: [Errno 5] Input/output error
2020-01-12 02:45:08.221 | 2104261139 | CRITICAL | brokkr.monitor | OSError caught at main level: [Errno 5] Input/output error
2020-01-12 02:45:08.222 | 2104261140 | INFO | brokkr.monitor | Details:
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 75, in start_monitoring
    record_status_data(output_path, verbose=verbose)
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 49, in record_status_data
    status_data = get_status_data()
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 39, in get_status_data
    output_data = item.fn()
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 244, in get_sunsaver_data
    register_data = read_raw_sunsaver_data(**kwargs)
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 160, in read_raw_sunsaver_data
    if mppt_client.connect():
  File "/home/thor/dev/brokkrenv/lib/python3.7/site-packages/pymodbus/client/sync.py", line 481, in connect
    parity=self.parity)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 286, in open
    self._update_dtr_state()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 634, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
OSError: [Errno 5] Input/output error
2020-01-12 02:46:08.221 | 2104321139 | CRITICAL | brokkr.monitor | OSError caught at main level: [Errno 5] Input/output error
2020-01-12 02:46:08.223 | 2104321141 | INFO | brokkr.monitor | Details:
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 75, in start_monitoring
    record_status_data(output_path, verbose=verbose)
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 49, in record_status_data
    status_data = get_status_data()
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 39, in get_status_data
    output_data = item.fn()
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 244, in get_sunsaver_data
    register_data = read_raw_sunsaver_data(**kwargs)
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 160, in read_raw_sunsaver_data
    if mppt_client.connect():
  File "/home/thor/dev/brokkrenv/lib/python3.7/site-packages/pymodbus/client/sync.py", line 481, in connect
    parity=self.parity)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 286, in open
    self._update_dtr_state()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 634, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
OSError: [Errno 5] Input/output error
2020-01-12 02:47:08.221 | 2104381139 | CRITICAL | brokkr.monitor | OSError caught at main level: [Errno 5] Input/output error
2020-01-12 02:47:08.222 | 2104381140 | INFO | brokkr.monitor | Details:
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 75, in start_monitoring
    record_status_data(output_path, verbose=verbose)
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 49, in record_status_data
    status_data = get_status_data()
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 39, in get_status_data
    output_data = item.fn()
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 244, in get_sunsaver_data
    register_data = read_raw_sunsaver_data(**kwargs)
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 160, in read_raw_sunsaver_data
    if mppt_client.connect():
  File "/home/thor/dev/brokkrenv/lib/python3.7/site-packages/pymodbus/client/sync.py", line 481, in connect
    parity=self.parity)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 286, in open
    self._update_dtr_state()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 634, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
OSError: [Errno 5] Input/output error
2020-01-12 02:48:08.221 | 2104441139 | CRITICAL | brokkr.monitor | OSError caught at main level: [Errno 5] Input/output error
2020-01-12 02:48:08.223 | 2104441141 | INFO | brokkr.monitor | Details:
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 75, in start_monitoring
    record_status_data(output_path, verbose=verbose)
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 49, in record_status_data
    status_data = get_status_data()
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 39, in get_status_data
    output_data = item.fn()
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 244, in get_sunsaver_data
    register_data = read_raw_sunsaver_data(**kwargs)
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 160, in read_raw_sunsaver_data
    if mppt_client.connect():
  File "/home/thor/dev/brokkrenv/lib/python3.7/site-packages/pymodbus/client/sync.py", line 481, in connect
    parity=self.parity)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 286, in open
    self._update_dtr_state()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 634, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
OSError: [Errno 5] Input/output error
2020-01-12 02:49:08.221 | 2104501139 | CRITICAL | brokkr.monitor | OSError caught at main level: [Errno 5] Input/output error
2020-01-12 02:49:08.223 | 2104501141 | INFO | brokkr.monitor | Details:
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 75, in start_monitoring
    record_status_data(output_path, verbose=verbose)
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 49, in record_status_data
    status_data = get_status_data()
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 39, in get_status_data
    output_data = item.fn()
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 244, in get_sunsaver_data
    register_data = read_raw_sunsaver_data(**kwargs)
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 160, in read_raw_sunsaver_data
    if mppt_client.connect():
  File "/home/thor/dev/brokkrenv/lib/python3.7/site-packages/pymodbus/client/sync.py", line 481, in connect
    parity=self.parity)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 286, in open
    self._update_dtr_state()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 634, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
OSError: [Errno 5] Input/output error
2020-01-12 02:50:08.221 | 2104561139 | CRITICAL | brokkr.monitor | OSError caught at main level: [Errno 5] Input/output error
2020-01-12 02:50:08.223 | 2104561141 | INFO | brokkr.monitor | Details:
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 75, in start_monitoring
    record_status_data(output_path, verbose=verbose)
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 49, in record_status_data
    status_data = get_status_data()
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 39, in get_status_data
    output_data = item.fn()
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 244, in get_sunsaver_data
    register_data = read_raw_sunsaver_data(**kwargs)
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 160, in read_raw_sunsaver_data
    if mppt_client.connect():
  File "/home/thor/dev/brokkrenv/lib/python3.7/site-packages/pymodbus/client/sync.py", line 481, in connect
    parity=self.parity)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 286, in open
    self._update_dtr_state()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 634, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
OSError: [Errno 5] Input/output error
2020-01-12 02:51:08.221 | 2104621139 | CRITICAL | brokkr.monitor | OSError caught at main level: [Errno 5] Input/output error
2020-01-12 02:51:08.222 | 2104621140 | INFO | brokkr.monitor | Details:
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 75, in start_monitoring
    record_status_data(output_path, verbose=verbose)
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 49, in record_status_data
    status_data = get_status_data()
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 39, in get_status_data
    output_data = item.fn()
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 244, in get_sunsaver_data
    register_data = read_raw_sunsaver_data(**kwargs)
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 160, in read_raw_sunsaver_data
    if mppt_client.connect():
  File "/home/thor/dev/brokkrenv/lib/python3.7/site-packages/pymodbus/client/sync.py", line 481, in connect
    parity=self.parity)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 286, in open
    self._update_dtr_state()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 634, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
OSError: [Errno 5] Input/output error
2020-01-12 02:52:08.222 | 2104681140 | CRITICAL | brokkr.monitor | OSError caught at main level: [Errno 5] Input/output error
2020-01-12 02:52:08.223 | 2104681141 | INFO | brokkr.monitor | Details:
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 75, in start_monitoring
    record_status_data(output_path, verbose=verbose)
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 49, in record_status_data
    status_data = get_status_data()
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 39, in get_status_data
    output_data = item.fn()
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 244, in get_sunsaver_data
    register_data = read_raw_sunsaver_data(**kwargs)
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 160, in read_raw_sunsaver_data
    if mppt_client.connect():
  File "/home/thor/dev/brokkrenv/lib/python3.7/site-packages/pymodbus/client/sync.py", line 481, in connect
    parity=self.parity)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 286, in open
    self._update_dtr_state()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 634, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
OSError: [Errno 5] Input/output error
2020-01-12 02:53:08.221 | 2104741139 | CRITICAL | brokkr.monitor | OSError caught at main level: [Errno 5] Input/output error
2020-01-12 02:53:08.223 | 2104741140 | INFO | brokkr.monitor | Details:
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 75, in start_monitoring
    record_status_data(output_path, verbose=verbose)
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 49, in record_status_data
    status_data = get_status_data()
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 39, in get_status_data
    output_data = item.fn()
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 244, in get_sunsaver_data
    register_data = read_raw_sunsaver_data(**kwargs)
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 160, in read_raw_sunsaver_data
    if mppt_client.connect():
  File "/home/thor/dev/brokkrenv/lib/python3.7/site-packages/pymodbus/client/sync.py", line 481, in connect
    parity=self.parity)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 286, in open
    self._update_dtr_state()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 634, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
OSError: [Errno 5] Input/output error
2020-01-12 02:54:08.211 | 2104801129 | CRITICAL | brokkr.monitor | OSError caught at main level: [Errno 5] Input/output error
2020-01-12 02:54:08.212 | 2104801130 | INFO | brokkr.monitor | Details:
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 75, in start_monitoring
    record_status_data(output_path, verbose=verbose)
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 49, in record_status_data
    status_data = get_status_data()
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 39, in get_status_data
    output_data = item.fn()
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 244, in get_sunsaver_data
    register_data = read_raw_sunsaver_data(**kwargs)
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 160, in read_raw_sunsaver_data
    if mppt_client.connect():
  File "/home/thor/dev/brokkrenv/lib/python3.7/site-packages/pymodbus/client/sync.py", line 481, in connect
    parity=self.parity)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 286, in open
    self._update_dtr_state()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 634, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
OSError: [Errno 5] Input/output error
2020-01-12 02:55:08.221 | 2104861139 | CRITICAL | brokkr.monitor | OSError caught at main level: [Errno 5] Input/output error
2020-01-12 02:55:08.223 | 2104861141 | INFO | brokkr.monitor | Details:
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 75, in start_monitoring
    record_status_data(output_path, verbose=verbose)
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 49, in record_status_data
    status_data = get_status_data()
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 39, in get_status_data
    output_data = item.fn()
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 244, in get_sunsaver_data
    register_data = read_raw_sunsaver_data(**kwargs)
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 160, in read_raw_sunsaver_data
    if mppt_client.connect():
  File "/home/thor/dev/brokkrenv/lib/python3.7/site-packages/pymodbus/client/sync.py", line 481, in connect
    parity=self.parity)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 286, in open
    self._update_dtr_state()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 634, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
OSError: [Errno 5] Input/output error
2020-01-12 02:56:08.221 | 2104921139 | CRITICAL | brokkr.monitor | OSError caught at main level: [Errno 5] Input/output error
2020-01-12 02:56:08.223 | 2104921141 | INFO | brokkr.monitor | Details:
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 75, in start_monitoring
    record_status_data(output_path, verbose=verbose)
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 49, in record_status_data
    status_data = get_status_data()
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 39, in get_status_data
    output_data = item.fn()
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 244, in get_sunsaver_data
    register_data = read_raw_sunsaver_data(**kwargs)
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 160, in read_raw_sunsaver_data
    if mppt_client.connect():
  File "/home/thor/dev/brokkrenv/lib/python3.7/site-packages/pymodbus/client/sync.py", line 481, in connect
    parity=self.parity)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 286, in open
    self._update_dtr_state()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 634, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
OSError: [Errno 5] Input/output error
2020-01-12 02:57:08.221 | 2104981139 | CRITICAL | brokkr.monitor | OSError caught at main level: [Errno 5] Input/output error
2020-01-12 02:57:08.223 | 2104981141 | INFO | brokkr.monitor | Details:
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 75, in start_monitoring
    record_status_data(output_path, verbose=verbose)
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 49, in record_status_data
    status_data = get_status_data()
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 39, in get_status_data
    output_data = item.fn()
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 244, in get_sunsaver_data
    register_data = read_raw_sunsaver_data(**kwargs)
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 160, in read_raw_sunsaver_data
    if mppt_client.connect():
  File "/home/thor/dev/brokkrenv/lib/python3.7/site-packages/pymodbus/client/sync.py", line 481, in connect
    parity=self.parity)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 286, in open
    self._update_dtr_state()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 634, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
OSError: [Errno 5] Input/output error
2020-01-12 02:58:08.221 | 2105041139 | CRITICAL | brokkr.monitor | OSError caught at main level: [Errno 5] Input/output error
2020-01-12 02:58:08.223 | 2105041141 | INFO | brokkr.monitor | Details:
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 75, in start_monitoring
    record_status_data(output_path, verbose=verbose)
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 49, in record_status_data
    status_data = get_status_data()
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 39, in get_status_data
    output_data = item.fn()
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 244, in get_sunsaver_data
    register_data = read_raw_sunsaver_data(**kwargs)
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 160, in read_raw_sunsaver_data
    if mppt_client.connect():
  File "/home/thor/dev/brokkrenv/lib/python3.7/site-packages/pymodbus/client/sync.py", line 481, in connect
    parity=self.parity)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 286, in open
    self._update_dtr_state()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 634, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
OSError: [Errno 5] Input/output error
2020-01-12 02:59:08.222 | 2105101139 | CRITICAL | brokkr.monitor | OSError caught at main level: [Errno 5] Input/output error
2020-01-12 02:59:08.223 | 2105101141 | INFO | brokkr.monitor | Details:
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 75, in start_monitoring
    record_status_data(output_path, verbose=verbose)
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 49, in record_status_data
    status_data = get_status_data()
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 39, in get_status_data
    output_data = item.fn()
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 244, in get_sunsaver_data
    register_data = read_raw_sunsaver_data(**kwargs)
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 160, in read_raw_sunsaver_data
    if mppt_client.connect():
  File "/home/thor/dev/brokkrenv/lib/python3.7/site-packages/pymodbus/client/sync.py", line 481, in connect
    parity=self.parity)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 286, in open
    self._update_dtr_state()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 634, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
OSError: [Errno 5] Input/output error
2020-01-12 03:00:08.221 | 2105161139 | CRITICAL | brokkr.monitor | OSError caught at main level: [Errno 5] Input/output error
2020-01-12 03:00:08.222 | 2105161140 | INFO | brokkr.monitor | Details:
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 75, in start_monitoring
    record_status_data(output_path, verbose=verbose)
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 49, in record_status_data
    status_data = get_status_data()
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 39, in get_status_data
    output_data = item.fn()
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 244, in get_sunsaver_data
    register_data = read_raw_sunsaver_data(**kwargs)
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 160, in read_raw_sunsaver_data
    if mppt_client.connect():
  File "/home/thor/dev/brokkrenv/lib/python3.7/site-packages/pymodbus/client/sync.py", line 481, in connect
    parity=self.parity)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 286, in open
    self._update_dtr_state()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 634, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
OSError: [Errno 5] Input/output error
2020-01-12 03:01:08.221 | 2105221139 | CRITICAL | brokkr.monitor | OSError caught at main level: [Errno 5] Input/output error
2020-01-12 03:01:08.223 | 2105221141 | INFO | brokkr.monitor | Details:
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 75, in start_monitoring
    record_status_data(output_path, verbose=verbose)
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 49, in record_status_data
    status_data = get_status_data()
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 39, in get_status_data
    output_data = item.fn()
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 244, in get_sunsaver_data
    register_data = read_raw_sunsaver_data(**kwargs)
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 160, in read_raw_sunsaver_data
    if mppt_client.connect():
  File "/home/thor/dev/brokkrenv/lib/python3.7/site-packages/pymodbus/client/sync.py", line 481, in connect
    parity=self.parity)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 286, in open
    self._update_dtr_state()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 634, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
OSError: [Errno 5] Input/output error
2020-01-12 03:02:08.222 | 2105281140 | CRITICAL | brokkr.monitor | OSError caught at main level: [Errno 5] Input/output error
2020-01-12 03:02:08.233 | 2105281151 | INFO | brokkr.monitor | Details:
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 75, in start_monitoring
    record_status_data(output_path, verbose=verbose)
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 49, in record_status_data
    status_data = get_status_data()
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 39, in get_status_data
    output_data = item.fn()
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 244, in get_sunsaver_data
    register_data = read_raw_sunsaver_data(**kwargs)
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 160, in read_raw_sunsaver_data
    if mppt_client.connect():
  File "/home/thor/dev/brokkrenv/lib/python3.7/site-packages/pymodbus/client/sync.py", line 481, in connect
    parity=self.parity)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 286, in open
    self._update_dtr_state()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 634, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
OSError: [Errno 5] Input/output error
2020-01-12 03:03:08.221 | 2105341139 | CRITICAL | brokkr.monitor | OSError caught at main level: [Errno 5] Input/output error
2020-01-12 03:03:08.223 | 2105341140 | INFO | brokkr.monitor | Details:
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 75, in start_monitoring
    record_status_data(output_path, verbose=verbose)
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 49, in record_status_data
    status_data = get_status_data()
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 39, in get_status_data
    output_data = item.fn()
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 244, in get_sunsaver_data
    register_data = read_raw_sunsaver_data(**kwargs)
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 160, in read_raw_sunsaver_data
    if mppt_client.connect():
  File "/home/thor/dev/brokkrenv/lib/python3.7/site-packages/pymodbus/client/sync.py", line 481, in connect
    parity=self.parity)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 286, in open
    self._update_dtr_state()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 634, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
OSError: [Errno 5] Input/output error
2020-01-12 03:04:08.212 | 2105401129 | CRITICAL | brokkr.monitor | OSError caught at main level: [Errno 5] Input/output error
2020-01-12 03:04:08.213 | 2105401130 | INFO | brokkr.monitor | Details:
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 75, in start_monitoring
    record_status_data(output_path, verbose=verbose)
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 49, in record_status_data
    status_data = get_status_data()
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 39, in get_status_data
    output_data = item.fn()
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 244, in get_sunsaver_data
    register_data = read_raw_sunsaver_data(**kwargs)
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 160, in read_raw_sunsaver_data
    if mppt_client.connect():
  File "/home/thor/dev/brokkrenv/lib/python3.7/site-packages/pymodbus/client/sync.py", line 481, in connect
    parity=self.parity)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 286, in open
    self._update_dtr_state()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 634, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
OSError: [Errno 5] Input/output error
2020-01-12 03:05:08.207 | 2105461125 | CRITICAL | brokkr.monitor | OSError caught at main level: [Errno 5] Input/output error
2020-01-12 03:05:08.207 | 2105461125 | INFO | brokkr.monitor | Details:
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 75, in start_monitoring
    record_status_data(output_path, verbose=verbose)
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 49, in record_status_data
    status_data = get_status_data()
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 39, in get_status_data
    output_data = item.fn()
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 244, in get_sunsaver_data
    register_data = read_raw_sunsaver_data(**kwargs)
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 160, in read_raw_sunsaver_data
    if mppt_client.connect():
  File "/home/thor/dev/brokkrenv/lib/python3.7/site-packages/pymodbus/client/sync.py", line 481, in connect
    parity=self.parity)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 286, in open
    self._update_dtr_state()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 634, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
OSError: [Errno 5] Input/output error
2020-01-12 03:06:08.221 | 2105521139 | CRITICAL | brokkr.monitor | OSError caught at main level: [Errno 5] Input/output error
2020-01-12 03:06:08.223 | 2105521141 | INFO | brokkr.monitor | Details:
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 75, in start_monitoring
    record_status_data(output_path, verbose=verbose)
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 49, in record_status_data
    status_data = get_status_data()
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 39, in get_status_data
    output_data = item.fn()
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 244, in get_sunsaver_data
    register_data = read_raw_sunsaver_data(**kwargs)
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 160, in read_raw_sunsaver_data
    if mppt_client.connect():
  File "/home/thor/dev/brokkrenv/lib/python3.7/site-packages/pymodbus/client/sync.py", line 481, in connect
    parity=self.parity)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 286, in open
    self._update_dtr_state()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 634, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
OSError: [Errno 5] Input/output error
2020-01-12 03:07:08.221 | 2105581139 | CRITICAL | brokkr.monitor | OSError caught at main level: [Errno 5] Input/output error
2020-01-12 03:07:08.222 | 2105581140 | INFO | brokkr.monitor | Details:
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 75, in start_monitoring
    record_status_data(output_path, verbose=verbose)
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 49, in record_status_data
    status_data = get_status_data()
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 39, in get_status_data
    output_data = item.fn()
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 244, in get_sunsaver_data
    register_data = read_raw_sunsaver_data(**kwargs)
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 160, in read_raw_sunsaver_data
    if mppt_client.connect():
  File "/home/thor/dev/brokkrenv/lib/python3.7/site-packages/pymodbus/client/sync.py", line 481, in connect
    parity=self.parity)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 286, in open
    self._update_dtr_state()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 634, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
OSError: [Errno 5] Input/output error
2020-01-12 03:08:08.221 | 2105641139 | CRITICAL | brokkr.monitor | OSError caught at main level: [Errno 5] Input/output error
2020-01-12 03:08:08.223 | 2105641141 | INFO | brokkr.monitor | Details:
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 75, in start_monitoring
    record_status_data(output_path, verbose=verbose)
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 49, in record_status_data
    status_data = get_status_data()
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 39, in get_status_data
    output_data = item.fn()
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 244, in get_sunsaver_data
    register_data = read_raw_sunsaver_data(**kwargs)
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 160, in read_raw_sunsaver_data
    if mppt_client.connect():
  File "/home/thor/dev/brokkrenv/lib/python3.7/site-packages/pymodbus/client/sync.py", line 481, in connect
    parity=self.parity)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 286, in open
    self._update_dtr_state()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 634, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
OSError: [Errno 5] Input/output error
2020-01-12 03:09:08.222 | 2105701140 | CRITICAL | brokkr.monitor | OSError caught at main level: [Errno 5] Input/output error
2020-01-12 03:09:08.223 | 2105701141 | INFO | brokkr.monitor | Details:
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 75, in start_monitoring
    record_status_data(output_path, verbose=verbose)
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 49, in record_status_data
    status_data = get_status_data()
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 39, in get_status_data
    output_data = item.fn()
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 244, in get_sunsaver_data
    register_data = read_raw_sunsaver_data(**kwargs)
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 160, in read_raw_sunsaver_data
    if mppt_client.connect():
  File "/home/thor/dev/brokkrenv/lib/python3.7/site-packages/pymodbus/client/sync.py", line 481, in connect
    parity=self.parity)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 286, in open
    self._update_dtr_state()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 634, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
OSError: [Errno 5] Input/output error
2020-01-12 03:10:08.222 | 2105761140 | CRITICAL | brokkr.monitor | OSError caught at main level: [Errno 5] Input/output error
2020-01-12 03:10:08.224 | 2105761142 | INFO | brokkr.monitor | Details:
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 75, in start_monitoring
    record_status_data(output_path, verbose=verbose)
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 49, in record_status_data
    status_data = get_status_data()
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 39, in get_status_data
    output_data = item.fn()
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 244, in get_sunsaver_data
    register_data = read_raw_sunsaver_data(**kwargs)
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 160, in read_raw_sunsaver_data
    if mppt_client.connect():
  File "/home/thor/dev/brokkrenv/lib/python3.7/site-packages/pymodbus/client/sync.py", line 481, in connect
    parity=self.parity)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 286, in open
    self._update_dtr_state()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 634, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
OSError: [Errno 5] Input/output error
2020-01-12 03:11:08.223 | 2105821140 | CRITICAL | brokkr.monitor | OSError caught at main level: [Errno 5] Input/output error
2020-01-12 03:11:08.224 | 2105821142 | INFO | brokkr.monitor | Details:
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 75, in start_monitoring
    record_status_data(output_path, verbose=verbose)
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 49, in record_status_data
    status_data = get_status_data()
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 39, in get_status_data
    output_data = item.fn()
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 244, in get_sunsaver_data
    register_data = read_raw_sunsaver_data(**kwargs)
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 160, in read_raw_sunsaver_data
    if mppt_client.connect():
  File "/home/thor/dev/brokkrenv/lib/python3.7/site-packages/pymodbus/client/sync.py", line 481, in connect
    parity=self.parity)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 286, in open
    self._update_dtr_state()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 634, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
OSError: [Errno 5] Input/output error
2020-01-12 03:12:08.222 | 2105881140 | CRITICAL | brokkr.monitor | OSError caught at main level: [Errno 5] Input/output error
2020-01-12 03:12:08.224 | 2105881142 | INFO | brokkr.monitor | Details:
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 75, in start_monitoring
    record_status_data(output_path, verbose=verbose)
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 49, in record_status_data
    status_data = get_status_data()
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 39, in get_status_data
    output_data = item.fn()
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 244, in get_sunsaver_data
    register_data = read_raw_sunsaver_data(**kwargs)
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 160, in read_raw_sunsaver_data
    if mppt_client.connect():
  File "/home/thor/dev/brokkrenv/lib/python3.7/site-packages/pymodbus/client/sync.py", line 481, in connect
    parity=self.parity)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 286, in open
    self._update_dtr_state()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 634, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
OSError: [Errno 5] Input/output error
2020-01-12 03:13:08.222 | 2105941140 | CRITICAL | brokkr.monitor | OSError caught at main level: [Errno 5] Input/output error
2020-01-12 03:13:08.224 | 2105941142 | INFO | brokkr.monitor | Details:
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 75, in start_monitoring
    record_status_data(output_path, verbose=verbose)
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 49, in record_status_data
    status_data = get_status_data()
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 39, in get_status_data
    output_data = item.fn()
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 244, in get_sunsaver_data
    register_data = read_raw_sunsaver_data(**kwargs)
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 160, in read_raw_sunsaver_data
    if mppt_client.connect():
  File "/home/thor/dev/brokkrenv/lib/python3.7/site-packages/pymodbus/client/sync.py", line 481, in connect
    parity=self.parity)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 286, in open
    self._update_dtr_state()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 634, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
OSError: [Errno 5] Input/output error
2020-01-12 03:14:08.211 | 2106001129 | CRITICAL | brokkr.monitor | OSError caught at main level: [Errno 5] Input/output error
2020-01-12 03:14:08.211 | 2106001129 | INFO | brokkr.monitor | Details:
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 75, in start_monitoring
    record_status_data(output_path, verbose=verbose)
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 49, in record_status_data
    status_data = get_status_data()
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 39, in get_status_data
    output_data = item.fn()
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 244, in get_sunsaver_data
    register_data = read_raw_sunsaver_data(**kwargs)
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 160, in read_raw_sunsaver_data
    if mppt_client.connect():
  File "/home/thor/dev/brokkrenv/lib/python3.7/site-packages/pymodbus/client/sync.py", line 481, in connect
    parity=self.parity)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 286, in open
    self._update_dtr_state()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 634, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
OSError: [Errno 5] Input/output error
2020-01-12 03:15:08.222 | 2106061140 | CRITICAL | brokkr.monitor | OSError caught at main level: [Errno 5] Input/output error
2020-01-12 03:15:08.224 | 2106061142 | INFO | brokkr.monitor | Details:
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 75, in start_monitoring
    record_status_data(output_path, verbose=verbose)
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 49, in record_status_data
    status_data = get_status_data()
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 39, in get_status_data
    output_data = item.fn()
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 244, in get_sunsaver_data
    register_data = read_raw_sunsaver_data(**kwargs)
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 160, in read_raw_sunsaver_data
    if mppt_client.connect():
  File "/home/thor/dev/brokkrenv/lib/python3.7/site-packages/pymodbus/client/sync.py", line 481, in connect
    parity=self.parity)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 286, in open
    self._update_dtr_state()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 634, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
OSError: [Errno 5] Input/output error
2020-01-12 03:16:08.222 | 2106121140 | CRITICAL | brokkr.monitor | OSError caught at main level: [Errno 5] Input/output error
2020-01-12 03:16:08.223 | 2106121141 | INFO | brokkr.monitor | Details:
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 75, in start_monitoring
    record_status_data(output_path, verbose=verbose)
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 49, in record_status_data
    status_data = get_status_data()
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 39, in get_status_data
    output_data = item.fn()
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 244, in get_sunsaver_data
    register_data = read_raw_sunsaver_data(**kwargs)
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 160, in read_raw_sunsaver_data
    if mppt_client.connect():
  File "/home/thor/dev/brokkrenv/lib/python3.7/site-packages/pymodbus/client/sync.py", line 481, in connect
    parity=self.parity)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 286, in open
    self._update_dtr_state()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 634, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
OSError: [Errno 5] Input/output error
2020-01-12 03:17:08.222 | 2106181139 | CRITICAL | brokkr.monitor | OSError caught at main level: [Errno 5] Input/output error
2020-01-12 03:17:08.223 | 2106181141 | INFO | brokkr.monitor | Details:
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 75, in start_monitoring
    record_status_data(output_path, verbose=verbose)
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 49, in record_status_data
    status_data = get_status_data()
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 39, in get_status_data
    output_data = item.fn()
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 244, in get_sunsaver_data
    register_data = read_raw_sunsaver_data(**kwargs)
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 160, in read_raw_sunsaver_data
    if mppt_client.connect():
  File "/home/thor/dev/brokkrenv/lib/python3.7/site-packages/pymodbus/client/sync.py", line 481, in connect
    parity=self.parity)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 286, in open
    self._update_dtr_state()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 634, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
OSError: [Errno 5] Input/output error
2020-01-12 03:18:08.222 | 2106241140 | CRITICAL | brokkr.monitor | OSError caught at main level: [Errno 5] Input/output error
2020-01-12 03:18:08.223 | 2106241141 | INFO | brokkr.monitor | Details:
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 75, in start_monitoring
    record_status_data(output_path, verbose=verbose)
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 49, in record_status_data
    status_data = get_status_data()
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 39, in get_status_data
    output_data = item.fn()
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 244, in get_sunsaver_data
    register_data = read_raw_sunsaver_data(**kwargs)
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 160, in read_raw_sunsaver_data
    if mppt_client.connect():
  File "/home/thor/dev/brokkrenv/lib/python3.7/site-packages/pymodbus/client/sync.py", line 481, in connect
    parity=self.parity)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 286, in open
    self._update_dtr_state()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 634, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
OSError: [Errno 5] Input/output error
2020-01-12 03:19:08.222 | 2106301140 | CRITICAL | brokkr.monitor | OSError caught at main level: [Errno 5] Input/output error
2020-01-12 03:19:08.223 | 2106301141 | INFO | brokkr.monitor | Details:
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 75, in start_monitoring
    record_status_data(output_path, verbose=verbose)
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 49, in record_status_data
    status_data = get_status_data()
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 39, in get_status_data
    output_data = item.fn()
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 244, in get_sunsaver_data
    register_data = read_raw_sunsaver_data(**kwargs)
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 160, in read_raw_sunsaver_data
    if mppt_client.connect():
  File "/home/thor/dev/brokkrenv/lib/python3.7/site-packages/pymodbus/client/sync.py", line 481, in connect
    parity=self.parity)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 286, in open
    self._update_dtr_state()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 634, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
OSError: [Errno 5] Input/output error
2020-01-12 03:20:08.222 | 2106361140 | CRITICAL | brokkr.monitor | OSError caught at main level: [Errno 5] Input/output error
2020-01-12 03:20:08.231 | 2106361149 | INFO | brokkr.monitor | Details:
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 75, in start_monitoring
    record_status_data(output_path, verbose=verbose)
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 49, in record_status_data
    status_data = get_status_data()
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 39, in get_status_data
    output_data = item.fn()
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 244, in get_sunsaver_data
    register_data = read_raw_sunsaver_data(**kwargs)
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 160, in read_raw_sunsaver_data
    if mppt_client.connect():
  File "/home/thor/dev/brokkrenv/lib/python3.7/site-packages/pymodbus/client/sync.py", line 481, in connect
    parity=self.parity)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 286, in open
    self._update_dtr_state()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 634, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
OSError: [Errno 5] Input/output error
2020-01-12 03:21:08.221 | 2106421139 | CRITICAL | brokkr.monitor | OSError caught at main level: [Errno 5] Input/output error
2020-01-12 03:21:08.223 | 2106421141 | INFO | brokkr.monitor | Details:
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 75, in start_monitoring
    record_status_data(output_path, verbose=verbose)
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 49, in record_status_data
    status_data = get_status_data()
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 39, in get_status_data
    output_data = item.fn()
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 244, in get_sunsaver_data
    register_data = read_raw_sunsaver_data(**kwargs)
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 160, in read_raw_sunsaver_data
    if mppt_client.connect():
  File "/home/thor/dev/brokkrenv/lib/python3.7/site-packages/pymodbus/client/sync.py", line 481, in connect
    parity=self.parity)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 286, in open
    self._update_dtr_state()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 634, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
OSError: [Errno 5] Input/output error
2020-01-12 03:22:08.221 | 2106481139 | CRITICAL | brokkr.monitor | OSError caught at main level: [Errno 5] Input/output error
2020-01-12 03:22:08.223 | 2106481141 | INFO | brokkr.monitor | Details:
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 75, in start_monitoring
    record_status_data(output_path, verbose=verbose)
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 49, in record_status_data
    status_data = get_status_data()
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 39, in get_status_data
    output_data = item.fn()
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 244, in get_sunsaver_data
    register_data = read_raw_sunsaver_data(**kwargs)
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 160, in read_raw_sunsaver_data
    if mppt_client.connect():
  File "/home/thor/dev/brokkrenv/lib/python3.7/site-packages/pymodbus/client/sync.py", line 481, in connect
    parity=self.parity)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 286, in open
    self._update_dtr_state()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 634, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
OSError: [Errno 5] Input/output error
2020-01-12 03:23:08.221 | 2106541139 | CRITICAL | brokkr.monitor | OSError caught at main level: [Errno 5] Input/output error
2020-01-12 03:23:08.223 | 2106541141 | INFO | brokkr.monitor | Details:
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 75, in start_monitoring
    record_status_data(output_path, verbose=verbose)
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 49, in record_status_data
    status_data = get_status_data()
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 39, in get_status_data
    output_data = item.fn()
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 244, in get_sunsaver_data
    register_data = read_raw_sunsaver_data(**kwargs)
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 160, in read_raw_sunsaver_data
    if mppt_client.connect():
  File "/home/thor/dev/brokkrenv/lib/python3.7/site-packages/pymodbus/client/sync.py", line 481, in connect
    parity=self.parity)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 286, in open
    self._update_dtr_state()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 634, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
OSError: [Errno 5] Input/output error
2020-01-12 03:24:08.212 | 2106601130 | CRITICAL | brokkr.monitor | OSError caught at main level: [Errno 5] Input/output error
2020-01-12 03:24:08.218 | 2106601136 | INFO | brokkr.monitor | Details:
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 75, in start_monitoring
    record_status_data(output_path, verbose=verbose)
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 49, in record_status_data
    status_data = get_status_data()
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 39, in get_status_data
    output_data = item.fn()
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 244, in get_sunsaver_data
    register_data = read_raw_sunsaver_data(**kwargs)
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 160, in read_raw_sunsaver_data
    if mppt_client.connect():
  File "/home/thor/dev/brokkrenv/lib/python3.7/site-packages/pymodbus/client/sync.py", line 481, in connect
    parity=self.parity)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 286, in open
    self._update_dtr_state()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 634, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
OSError: [Errno 5] Input/output error
2020-01-12 03:25:08.221 | 2106661139 | CRITICAL | brokkr.monitor | OSError caught at main level: [Errno 5] Input/output error
2020-01-12 03:25:08.233 | 2106661151 | INFO | brokkr.monitor | Details:
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 75, in start_monitoring
    record_status_data(output_path, verbose=verbose)
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 49, in record_status_data
    status_data = get_status_data()
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 39, in get_status_data
    output_data = item.fn()
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 244, in get_sunsaver_data
    register_data = read_raw_sunsaver_data(**kwargs)
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 160, in read_raw_sunsaver_data
    if mppt_client.connect():
  File "/home/thor/dev/brokkrenv/lib/python3.7/site-packages/pymodbus/client/sync.py", line 481, in connect
    parity=self.parity)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 286, in open
    self._update_dtr_state()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 634, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
OSError: [Errno 5] Input/output error
2020-01-12 03:26:08.221 | 2106721139 | CRITICAL | brokkr.monitor | OSError caught at main level: [Errno 5] Input/output error
2020-01-12 03:26:08.233 | 2106721150 | INFO | brokkr.monitor | Details:
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 75, in start_monitoring
    record_status_data(output_path, verbose=verbose)
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 49, in record_status_data
    status_data = get_status_data()
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 39, in get_status_data
    output_data = item.fn()
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 244, in get_sunsaver_data
    register_data = read_raw_sunsaver_data(**kwargs)
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 160, in read_raw_sunsaver_data
    if mppt_client.connect():
  File "/home/thor/dev/brokkrenv/lib/python3.7/site-packages/pymodbus/client/sync.py", line 481, in connect
    parity=self.parity)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 286, in open
    self._update_dtr_state()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 634, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
OSError: [Errno 5] Input/output error
2020-01-12 03:27:08.221 | 2106781139 | CRITICAL | brokkr.monitor | OSError caught at main level: [Errno 5] Input/output error
2020-01-12 03:27:08.223 | 2106781141 | INFO | brokkr.monitor | Details:
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 75, in start_monitoring
    record_status_data(output_path, verbose=verbose)
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 49, in record_status_data
    status_data = get_status_data()
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 39, in get_status_data
    output_data = item.fn()
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 244, in get_sunsaver_data
    register_data = read_raw_sunsaver_data(**kwargs)
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 160, in read_raw_sunsaver_data
    if mppt_client.connect():
  File "/home/thor/dev/brokkrenv/lib/python3.7/site-packages/pymodbus/client/sync.py", line 481, in connect
    parity=self.parity)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 286, in open
    self._update_dtr_state()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 634, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
OSError: [Errno 5] Input/output error
2020-01-12 03:28:08.221 | 2106841139 | CRITICAL | brokkr.monitor | OSError caught at main level: [Errno 5] Input/output error
2020-01-12 03:28:08.223 | 2106841141 | INFO | brokkr.monitor | Details:
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 75, in start_monitoring
    record_status_data(output_path, verbose=verbose)
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 49, in record_status_data
    status_data = get_status_data()
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 39, in get_status_data
    output_data = item.fn()
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 244, in get_sunsaver_data
    register_data = read_raw_sunsaver_data(**kwargs)
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 160, in read_raw_sunsaver_data
    if mppt_client.connect():
  File "/home/thor/dev/brokkrenv/lib/python3.7/site-packages/pymodbus/client/sync.py", line 481, in connect
    parity=self.parity)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 286, in open
    self._update_dtr_state()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 634, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
OSError: [Errno 5] Input/output error
2020-01-12 03:29:08.221 | 2106901139 | CRITICAL | brokkr.monitor | OSError caught at main level: [Errno 5] Input/output error
2020-01-12 03:29:08.222 | 2106901140 | INFO | brokkr.monitor | Details:
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 75, in start_monitoring
    record_status_data(output_path, verbose=verbose)
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 49, in record_status_data
    status_data = get_status_data()
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 39, in get_status_data
    output_data = item.fn()
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 244, in get_sunsaver_data
    register_data = read_raw_sunsaver_data(**kwargs)
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 160, in read_raw_sunsaver_data
    if mppt_client.connect():
  File "/home/thor/dev/brokkrenv/lib/python3.7/site-packages/pymodbus/client/sync.py", line 481, in connect
    parity=self.parity)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 286, in open
    self._update_dtr_state()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 634, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
OSError: [Errno 5] Input/output error
2020-01-12 03:30:08.221 | 2106961139 | CRITICAL | brokkr.monitor | OSError caught at main level: [Errno 5] Input/output error
2020-01-12 03:30:08.223 | 2106961141 | INFO | brokkr.monitor | Details:
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 75, in start_monitoring
    record_status_data(output_path, verbose=verbose)
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 49, in record_status_data
    status_data = get_status_data()
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 39, in get_status_data
    output_data = item.fn()
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 244, in get_sunsaver_data
    register_data = read_raw_sunsaver_data(**kwargs)
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 160, in read_raw_sunsaver_data
    if mppt_client.connect():
  File "/home/thor/dev/brokkrenv/lib/python3.7/site-packages/pymodbus/client/sync.py", line 481, in connect
    parity=self.parity)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 286, in open
    self._update_dtr_state()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 634, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
OSError: [Errno 5] Input/output error
2020-01-12 03:31:08.221 | 2107021139 | CRITICAL | brokkr.monitor | OSError caught at main level: [Errno 5] Input/output error
2020-01-12 03:31:08.222 | 2107021140 | INFO | brokkr.monitor | Details:
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 75, in start_monitoring
    record_status_data(output_path, verbose=verbose)
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 49, in record_status_data
    status_data = get_status_data()
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 39, in get_status_data
    output_data = item.fn()
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 244, in get_sunsaver_data
    register_data = read_raw_sunsaver_data(**kwargs)
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 160, in read_raw_sunsaver_data
    if mppt_client.connect():
  File "/home/thor/dev/brokkrenv/lib/python3.7/site-packages/pymodbus/client/sync.py", line 481, in connect
    parity=self.parity)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 286, in open
    self._update_dtr_state()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 634, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
OSError: [Errno 5] Input/output error
2020-01-12 03:32:08.222 | 2107081139 | CRITICAL | brokkr.monitor | OSError caught at main level: [Errno 5] Input/output error
2020-01-12 03:32:08.223 | 2107081141 | INFO | brokkr.monitor | Details:
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 75, in start_monitoring
    record_status_data(output_path, verbose=verbose)
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 49, in record_status_data
    status_data = get_status_data()
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 39, in get_status_data
    output_data = item.fn()
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 244, in get_sunsaver_data
    register_data = read_raw_sunsaver_data(**kwargs)
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 160, in read_raw_sunsaver_data
    if mppt_client.connect():
  File "/home/thor/dev/brokkrenv/lib/python3.7/site-packages/pymodbus/client/sync.py", line 481, in connect
    parity=self.parity)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 286, in open
    self._update_dtr_state()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 634, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
OSError: [Errno 5] Input/output error
2020-01-12 03:33:08.221 | 2107141139 | CRITICAL | brokkr.monitor | OSError caught at main level: [Errno 5] Input/output error
2020-01-12 03:33:08.223 | 2107141141 | INFO | brokkr.monitor | Details:
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 75, in start_monitoring
    record_status_data(output_path, verbose=verbose)
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 49, in record_status_data
    status_data = get_status_data()
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 39, in get_status_data
    output_data = item.fn()
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 244, in get_sunsaver_data
    register_data = read_raw_sunsaver_data(**kwargs)
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 160, in read_raw_sunsaver_data
    if mppt_client.connect():
  File "/home/thor/dev/brokkrenv/lib/python3.7/site-packages/pymodbus/client/sync.py", line 481, in connect
    parity=self.parity)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 286, in open
    self._update_dtr_state()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 634, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
OSError: [Errno 5] Input/output error
2020-01-12 03:34:08.211 | 2107201129 | CRITICAL | brokkr.monitor | OSError caught at main level: [Errno 5] Input/output error
2020-01-12 03:34:08.212 | 2107201130 | INFO | brokkr.monitor | Details:
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 75, in start_monitoring
    record_status_data(output_path, verbose=verbose)
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 49, in record_status_data
    status_data = get_status_data()
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 39, in get_status_data
    output_data = item.fn()
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 244, in get_sunsaver_data
    register_data = read_raw_sunsaver_data(**kwargs)
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 160, in read_raw_sunsaver_data
    if mppt_client.connect():
  File "/home/thor/dev/brokkrenv/lib/python3.7/site-packages/pymodbus/client/sync.py", line 481, in connect
    parity=self.parity)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 286, in open
    self._update_dtr_state()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 634, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
OSError: [Errno 5] Input/output error
2020-01-12 03:35:08.221 | 2107261139 | CRITICAL | brokkr.monitor | OSError caught at main level: [Errno 5] Input/output error
2020-01-12 03:35:08.223 | 2107261141 | INFO | brokkr.monitor | Details:
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 75, in start_monitoring
    record_status_data(output_path, verbose=verbose)
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 49, in record_status_data
    status_data = get_status_data()
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 39, in get_status_data
    output_data = item.fn()
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 244, in get_sunsaver_data
    register_data = read_raw_sunsaver_data(**kwargs)
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 160, in read_raw_sunsaver_data
    if mppt_client.connect():
  File "/home/thor/dev/brokkrenv/lib/python3.7/site-packages/pymodbus/client/sync.py", line 481, in connect
    parity=self.parity)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 286, in open
    self._update_dtr_state()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 634, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
OSError: [Errno 5] Input/output error
2020-01-12 03:36:08.221 | 2107321139 | CRITICAL | brokkr.monitor | OSError caught at main level: [Errno 5] Input/output error
2020-01-12 03:36:08.223 | 2107321141 | INFO | brokkr.monitor | Details:
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 75, in start_monitoring
    record_status_data(output_path, verbose=verbose)
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 49, in record_status_data
    status_data = get_status_data()
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 39, in get_status_data
    output_data = item.fn()
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 244, in get_sunsaver_data
    register_data = read_raw_sunsaver_data(**kwargs)
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 160, in read_raw_sunsaver_data
    if mppt_client.connect():
  File "/home/thor/dev/brokkrenv/lib/python3.7/site-packages/pymodbus/client/sync.py", line 481, in connect
    parity=self.parity)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 286, in open
    self._update_dtr_state()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 634, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
OSError: [Errno 5] Input/output error
2020-01-12 03:37:08.221 | 2107381139 | CRITICAL | brokkr.monitor | OSError caught at main level: [Errno 5] Input/output error
2020-01-12 03:37:08.223 | 2107381141 | INFO | brokkr.monitor | Details:
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 75, in start_monitoring
    record_status_data(output_path, verbose=verbose)
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 49, in record_status_data
    status_data = get_status_data()
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 39, in get_status_data
    output_data = item.fn()
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 244, in get_sunsaver_data
    register_data = read_raw_sunsaver_data(**kwargs)
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 160, in read_raw_sunsaver_data
    if mppt_client.connect():
  File "/home/thor/dev/brokkrenv/lib/python3.7/site-packages/pymodbus/client/sync.py", line 481, in connect
    parity=self.parity)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 286, in open
    self._update_dtr_state()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 634, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
OSError: [Errno 5] Input/output error
2020-01-12 03:38:08.221 | 2107441139 | CRITICAL | brokkr.monitor | OSError caught at main level: [Errno 5] Input/output error
2020-01-12 03:38:08.223 | 2107441141 | INFO | brokkr.monitor | Details:
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 75, in start_monitoring
    record_status_data(output_path, verbose=verbose)
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 49, in record_status_data
    status_data = get_status_data()
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 39, in get_status_data
    output_data = item.fn()
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 244, in get_sunsaver_data
    register_data = read_raw_sunsaver_data(**kwargs)
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 160, in read_raw_sunsaver_data
    if mppt_client.connect():
  File "/home/thor/dev/brokkrenv/lib/python3.7/site-packages/pymodbus/client/sync.py", line 481, in connect
    parity=self.parity)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 286, in open
    self._update_dtr_state()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 634, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
OSError: [Errno 5] Input/output error
2020-01-12 03:39:08.221 | 2107501139 | CRITICAL | brokkr.monitor | OSError caught at main level: [Errno 5] Input/output error
2020-01-12 03:39:08.223 | 2107501141 | INFO | brokkr.monitor | Details:
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 75, in start_monitoring
    record_status_data(output_path, verbose=verbose)
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 49, in record_status_data
    status_data = get_status_data()
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 39, in get_status_data
    output_data = item.fn()
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 244, in get_sunsaver_data
    register_data = read_raw_sunsaver_data(**kwargs)
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 160, in read_raw_sunsaver_data
    if mppt_client.connect():
  File "/home/thor/dev/brokkrenv/lib/python3.7/site-packages/pymodbus/client/sync.py", line 481, in connect
    parity=self.parity)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 286, in open
    self._update_dtr_state()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 634, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
OSError: [Errno 5] Input/output error
2020-01-12 03:40:08.221 | 2107561139 | CRITICAL | brokkr.monitor | OSError caught at main level: [Errno 5] Input/output error
2020-01-12 03:40:08.223 | 2107561141 | INFO | brokkr.monitor | Details:
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 75, in start_monitoring
    record_status_data(output_path, verbose=verbose)
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 49, in record_status_data
    status_data = get_status_data()
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 39, in get_status_data
    output_data = item.fn()
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 244, in get_sunsaver_data
    register_data = read_raw_sunsaver_data(**kwargs)
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 160, in read_raw_sunsaver_data
    if mppt_client.connect():
  File "/home/thor/dev/brokkrenv/lib/python3.7/site-packages/pymodbus/client/sync.py", line 481, in connect
    parity=self.parity)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 286, in open
    self._update_dtr_state()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 634, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
OSError: [Errno 5] Input/output error
2020-01-12 03:41:08.221 | 2107621139 | CRITICAL | brokkr.monitor | OSError caught at main level: [Errno 5] Input/output error
2020-01-12 03:41:08.223 | 2107621141 | INFO | brokkr.monitor | Details:
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 75, in start_monitoring
    record_status_data(output_path, verbose=verbose)
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 49, in record_status_data
    status_data = get_status_data()
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 39, in get_status_data
    output_data = item.fn()
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 244, in get_sunsaver_data
    register_data = read_raw_sunsaver_data(**kwargs)
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 160, in read_raw_sunsaver_data
    if mppt_client.connect():
  File "/home/thor/dev/brokkrenv/lib/python3.7/site-packages/pymodbus/client/sync.py", line 481, in connect
    parity=self.parity)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 286, in open
    self._update_dtr_state()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 634, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
OSError: [Errno 5] Input/output error
2020-01-12 03:42:08.221 | 2107681139 | CRITICAL | brokkr.monitor | OSError caught at main level: [Errno 5] Input/output error
2020-01-12 03:42:08.223 | 2107681141 | INFO | brokkr.monitor | Details:
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 75, in start_monitoring
    record_status_data(output_path, verbose=verbose)
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 49, in record_status_data
    status_data = get_status_data()
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 39, in get_status_data
    output_data = item.fn()
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 244, in get_sunsaver_data
    register_data = read_raw_sunsaver_data(**kwargs)
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 160, in read_raw_sunsaver_data
    if mppt_client.connect():
  File "/home/thor/dev/brokkrenv/lib/python3.7/site-packages/pymodbus/client/sync.py", line 481, in connect
    parity=self.parity)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 286, in open
    self._update_dtr_state()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 634, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
OSError: [Errno 5] Input/output error
2020-01-12 03:43:08.221 | 2107741139 | CRITICAL | brokkr.monitor | OSError caught at main level: [Errno 5] Input/output error
2020-01-12 03:43:08.223 | 2107741141 | INFO | brokkr.monitor | Details:
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 75, in start_monitoring
    record_status_data(output_path, verbose=verbose)
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 49, in record_status_data
    status_data = get_status_data()
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 39, in get_status_data
    output_data = item.fn()
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 244, in get_sunsaver_data
    register_data = read_raw_sunsaver_data(**kwargs)
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 160, in read_raw_sunsaver_data
    if mppt_client.connect():
  File "/home/thor/dev/brokkrenv/lib/python3.7/site-packages/pymodbus/client/sync.py", line 481, in connect
    parity=self.parity)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 286, in open
    self._update_dtr_state()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 634, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
OSError: [Errno 5] Input/output error
2020-01-12 03:44:08.211 | 2107801129 | CRITICAL | brokkr.monitor | OSError caught at main level: [Errno 5] Input/output error
2020-01-12 03:44:08.214 | 2107801131 | INFO | brokkr.monitor | Details:
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 75, in start_monitoring
    record_status_data(output_path, verbose=verbose)
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 49, in record_status_data
    status_data = get_status_data()
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 39, in get_status_data
    output_data = item.fn()
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 244, in get_sunsaver_data
    register_data = read_raw_sunsaver_data(**kwargs)
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 160, in read_raw_sunsaver_data
    if mppt_client.connect():
  File "/home/thor/dev/brokkrenv/lib/python3.7/site-packages/pymodbus/client/sync.py", line 481, in connect
    parity=self.parity)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 286, in open
    self._update_dtr_state()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 634, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
OSError: [Errno 5] Input/output error
2020-01-12 03:45:08.222 | 2107861140 | CRITICAL | brokkr.monitor | OSError caught at main level: [Errno 5] Input/output error
2020-01-12 03:45:08.223 | 2107861141 | INFO | brokkr.monitor | Details:
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 75, in start_monitoring
    record_status_data(output_path, verbose=verbose)
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 49, in record_status_data
    status_data = get_status_data()
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 39, in get_status_data
    output_data = item.fn()
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 244, in get_sunsaver_data
    register_data = read_raw_sunsaver_data(**kwargs)
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 160, in read_raw_sunsaver_data
    if mppt_client.connect():
  File "/home/thor/dev/brokkrenv/lib/python3.7/site-packages/pymodbus/client/sync.py", line 481, in connect
    parity=self.parity)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 286, in open
    self._update_dtr_state()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 634, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
OSError: [Errno 5] Input/output error
2020-01-12 03:46:08.221 | 2107921139 | CRITICAL | brokkr.monitor | OSError caught at main level: [Errno 5] Input/output error
2020-01-12 03:46:08.223 | 2107921140 | INFO | brokkr.monitor | Details:
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 75, in start_monitoring
    record_status_data(output_path, verbose=verbose)
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 49, in record_status_data
    status_data = get_status_data()
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 39, in get_status_data
    output_data = item.fn()
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 244, in get_sunsaver_data
    register_data = read_raw_sunsaver_data(**kwargs)
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 160, in read_raw_sunsaver_data
    if mppt_client.connect():
  File "/home/thor/dev/brokkrenv/lib/python3.7/site-packages/pymodbus/client/sync.py", line 481, in connect
    parity=self.parity)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 286, in open
    self._update_dtr_state()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 634, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
OSError: [Errno 5] Input/output error
2020-01-12 03:47:08.221 | 2107981139 | CRITICAL | brokkr.monitor | OSError caught at main level: [Errno 5] Input/output error
2020-01-12 03:47:08.223 | 2107981141 | INFO | brokkr.monitor | Details:
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 75, in start_monitoring
    record_status_data(output_path, verbose=verbose)
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 49, in record_status_data
    status_data = get_status_data()
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 39, in get_status_data
    output_data = item.fn()
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 244, in get_sunsaver_data
    register_data = read_raw_sunsaver_data(**kwargs)
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 160, in read_raw_sunsaver_data
    if mppt_client.connect():
  File "/home/thor/dev/brokkrenv/lib/python3.7/site-packages/pymodbus/client/sync.py", line 481, in connect
    parity=self.parity)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 286, in open
    self._update_dtr_state()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 634, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
OSError: [Errno 5] Input/output error
2020-01-12 03:48:08.223 | 2108041141 | CRITICAL | brokkr.monitor | OSError caught at main level: [Errno 5] Input/output error
2020-01-12 03:48:08.225 | 2108041143 | INFO | brokkr.monitor | Details:
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 75, in start_monitoring
    record_status_data(output_path, verbose=verbose)
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 49, in record_status_data
    status_data = get_status_data()
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 39, in get_status_data
    output_data = item.fn()
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 244, in get_sunsaver_data
    register_data = read_raw_sunsaver_data(**kwargs)
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 160, in read_raw_sunsaver_data
    if mppt_client.connect():
  File "/home/thor/dev/brokkrenv/lib/python3.7/site-packages/pymodbus/client/sync.py", line 481, in connect
    parity=self.parity)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 286, in open
    self._update_dtr_state()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 634, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
OSError: [Errno 5] Input/output error
2020-01-12 03:49:08.222 | 2108101140 | CRITICAL | brokkr.monitor | OSError caught at main level: [Errno 5] Input/output error
2020-01-12 03:49:08.224 | 2108101141 | INFO | brokkr.monitor | Details:
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 75, in start_monitoring
    record_status_data(output_path, verbose=verbose)
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 49, in record_status_data
    status_data = get_status_data()
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 39, in get_status_data
    output_data = item.fn()
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 244, in get_sunsaver_data
    register_data = read_raw_sunsaver_data(**kwargs)
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 160, in read_raw_sunsaver_data
    if mppt_client.connect():
  File "/home/thor/dev/brokkrenv/lib/python3.7/site-packages/pymodbus/client/sync.py", line 481, in connect
    parity=self.parity)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 286, in open
    self._update_dtr_state()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 634, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
OSError: [Errno 5] Input/output error
2020-01-12 03:50:08.222 | 2108161140 | CRITICAL | brokkr.monitor | OSError caught at main level: [Errno 5] Input/output error
2020-01-12 03:50:08.223 | 2108161141 | INFO | brokkr.monitor | Details:
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 75, in start_monitoring
    record_status_data(output_path, verbose=verbose)
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 49, in record_status_data
    status_data = get_status_data()
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 39, in get_status_data
    output_data = item.fn()
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 244, in get_sunsaver_data
    register_data = read_raw_sunsaver_data(**kwargs)
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 160, in read_raw_sunsaver_data
    if mppt_client.connect():
  File "/home/thor/dev/brokkrenv/lib/python3.7/site-packages/pymodbus/client/sync.py", line 481, in connect
    parity=self.parity)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 286, in open
    self._update_dtr_state()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 634, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
OSError: [Errno 5] Input/output error
2020-01-12 03:51:08.222 | 2108221140 | CRITICAL | brokkr.monitor | OSError caught at main level: [Errno 5] Input/output error
2020-01-12 03:51:08.223 | 2108221141 | INFO | brokkr.monitor | Details:
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 75, in start_monitoring
    record_status_data(output_path, verbose=verbose)
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 49, in record_status_data
    status_data = get_status_data()
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 39, in get_status_data
    output_data = item.fn()
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 244, in get_sunsaver_data
    register_data = read_raw_sunsaver_data(**kwargs)
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 160, in read_raw_sunsaver_data
    if mppt_client.connect():
  File "/home/thor/dev/brokkrenv/lib/python3.7/site-packages/pymodbus/client/sync.py", line 481, in connect
    parity=self.parity)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 286, in open
    self._update_dtr_state()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 634, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
OSError: [Errno 5] Input/output error
2020-01-12 03:52:08.221 | 2108281139 | CRITICAL | brokkr.monitor | OSError caught at main level: [Errno 5] Input/output error
2020-01-12 03:52:08.223 | 2108281141 | INFO | brokkr.monitor | Details:
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 75, in start_monitoring
    record_status_data(output_path, verbose=verbose)
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 49, in record_status_data
    status_data = get_status_data()
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 39, in get_status_data
    output_data = item.fn()
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 244, in get_sunsaver_data
    register_data = read_raw_sunsaver_data(**kwargs)
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 160, in read_raw_sunsaver_data
    if mppt_client.connect():
  File "/home/thor/dev/brokkrenv/lib/python3.7/site-packages/pymodbus/client/sync.py", line 481, in connect
    parity=self.parity)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 286, in open
    self._update_dtr_state()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 634, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
OSError: [Errno 5] Input/output error
2020-01-12 03:53:08.221 | 2108341139 | CRITICAL | brokkr.monitor | OSError caught at main level: [Errno 5] Input/output error
2020-01-12 03:53:08.223 | 2108341141 | INFO | brokkr.monitor | Details:
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 75, in start_monitoring
    record_status_data(output_path, verbose=verbose)
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 49, in record_status_data
    status_data = get_status_data()
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 39, in get_status_data
    output_data = item.fn()
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 244, in get_sunsaver_data
    register_data = read_raw_sunsaver_data(**kwargs)
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 160, in read_raw_sunsaver_data
    if mppt_client.connect():
  File "/home/thor/dev/brokkrenv/lib/python3.7/site-packages/pymodbus/client/sync.py", line 481, in connect
    parity=self.parity)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 286, in open
    self._update_dtr_state()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 634, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
OSError: [Errno 5] Input/output error
2020-01-12 03:54:08.211 | 2108401128 | CRITICAL | brokkr.monitor | OSError caught at main level: [Errno 5] Input/output error
2020-01-12 03:54:08.211 | 2108401129 | INFO | brokkr.monitor | Details:
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 75, in start_monitoring
    record_status_data(output_path, verbose=verbose)
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 49, in record_status_data
    status_data = get_status_data()
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 39, in get_status_data
    output_data = item.fn()
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 244, in get_sunsaver_data
    register_data = read_raw_sunsaver_data(**kwargs)
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 160, in read_raw_sunsaver_data
    if mppt_client.connect():
  File "/home/thor/dev/brokkrenv/lib/python3.7/site-packages/pymodbus/client/sync.py", line 481, in connect
    parity=self.parity)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 286, in open
    self._update_dtr_state()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 634, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
OSError: [Errno 5] Input/output error
