2019-10-29 11:36:41.817 | 33 | INFO | brokkr.startup | Starting Brokkr...
2019-10-29 11:36:44.950 | 3166 | ERROR | brokkr.sunsaver | ModbusIOException reading register data for /dev/ttyUSB0: Modbus Error: [Input/Output] Modbus Error: [Invalid Message] Incomplete message received, expected at least 2 bytes (0 received)
2019-10-29 11:36:44.962 | 3178 | INFO | brokkr.sunsaver | Details: ModbusSerialClient(rtu baud[9600])
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 164, in read_raw_sunsaver_data
    raise register_data
pymodbus.exceptions.ModbusIOException: Modbus Error: [Input/Output] Modbus Error: [Invalid Message] Incomplete message received, expected at least 2 bytes (0 received)
2019-10-29 11:36:54.867 | 13083 | ERROR | brokkr.sunsaver | ModbusIOException reading register data for /dev/ttyUSB0: Modbus Error: [Input/Output] Modbus Error: [Invalid Message] Incomplete message received, expected at least 2 bytes (0 received)
2019-10-29 11:36:54.884 | 13100 | INFO | brokkr.sunsaver | Details: ModbusSerialClient(rtu baud[9600])
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 164, in read_raw_sunsaver_data
    raise register_data
pymodbus.exceptions.ModbusIOException: Modbus Error: [Input/Output] Modbus Error: [Invalid Message] Incomplete message received, expected at least 2 bytes (0 received)
2019-10-29 11:36:59.205 | 17421 | INFO | brokkr.startup | Interrupted by signal 2; terminating Brokkr
2019-10-29 11:40:16.784 | 31 | INFO | brokkr.startup | Starting Brokkr...
2019-10-29 11:40:19.874 | 3121 | ERROR | brokkr.sunsaver | ModbusIOException reading register data for /dev/ttyUSB0: Modbus Error: [Input/Output] Modbus Error: [Invalid Message] Incomplete message received, expected at least 2 bytes (0 received)
2019-10-29 11:40:19.896 | 3143 | INFO | brokkr.sunsaver | Details: ModbusSerialClient(rtu baud[9600])
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 164, in read_raw_sunsaver_data
    raise register_data
pymodbus.exceptions.ModbusIOException: Modbus Error: [Input/Output] Modbus Error: [Invalid Message] Incomplete message received, expected at least 2 bytes (0 received)
2019-10-29 11:40:29.835 | 13082 | ERROR | brokkr.sunsaver | ModbusIOException reading register data for /dev/ttyUSB0: Modbus Error: [Input/Output] Modbus Error: [Invalid Message] Incomplete message received, expected at least 2 bytes (0 received)
2019-10-29 11:40:29.861 | 13108 | INFO | brokkr.sunsaver | Details: ModbusSerialClient(rtu baud[9600])
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 164, in read_raw_sunsaver_data
    raise register_data
pymodbus.exceptions.ModbusIOException: Modbus Error: [Input/Output] Modbus Error: [Invalid Message] Incomplete message received, expected at least 2 bytes (0 received)
2019-10-29 11:40:33.617 | 16864 | INFO | brokkr.startup | Interrupted by signal 2; terminating Brokkr
2019-10-29 11:45:18.161 | 31 | INFO | brokkr.startup | Starting Brokkr...
2019-10-29 11:45:21.248 | 3118 | ERROR | brokkr.sunsaver | ModbusIOException reading register data for /dev/ttyUSB0: Modbus Error: [Input/Output] Modbus Error: [Invalid Message] Incomplete message received, expected at least 2 bytes (0 received)
2019-10-29 11:45:21.260 | 3131 | INFO | brokkr.sunsaver | Details: ModbusSerialClient(rtu baud[9600])
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 164, in read_raw_sunsaver_data
    raise register_data
pymodbus.exceptions.ModbusIOException: Modbus Error: [Input/Output] Modbus Error: [Invalid Message] Incomplete message received, expected at least 2 bytes (0 received)
2019-10-29 11:45:25.312 | 7183 | INFO | brokkr.startup | Interrupted by signal 2; terminating Brokkr
2019-10-29 13:05:25.222 | 74 | INFO | brokkr.startup | Starting Brokkr...
2019-10-29 13:05:28.407 | 3258 | ERROR | brokkr.sunsaver | ModbusIOException reading register data for /dev/ttyUSB0: Modbus Error: [Input/Output] Modbus Error: [Invalid Message] Incomplete message received, expected at least 2 bytes (0 received)
2019-10-29 13:05:28.408 | 3260 | INFO | brokkr.sunsaver | Details: ModbusSerialClient(rtu baud[9600])
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 164, in read_raw_sunsaver_data
    raise register_data
pymodbus.exceptions.ModbusIOException: Modbus Error: [Input/Output] Modbus Error: [Invalid Message] Incomplete message received, expected at least 2 bytes (0 received)
2019-10-29 13:09:49.165 | 264016 | INFO | brokkr.startup | Interrupted by signal 15; terminating Brokkr
2019-10-29 13:11:24.368 | 86 | INFO | brokkr.startup | Starting Brokkr...
2019-10-29 13:59:01.118 | 2856837 | INFO | brokkr.startup | Interrupted by signal 15; terminating Brokkr
2019-10-29 14:47:29.310 | 88 | INFO | brokkr.startup | Starting Brokkr...
2019-11-03 02:53:47.271 | 389178049 | INFO | brokkr.startup | Interrupted by signal 15; terminating Brokkr
2019-11-03 02:54:21.720 | 91 | INFO | brokkr.startup | Starting Brokkr...
2019-11-07 05:01:43.577 | 353241949 | INFO | brokkr.startup | Interrupted by signal 15; terminating Brokkr
2019-11-07 05:15:26.938 | 92 | INFO | brokkr.startup | Starting Brokkr...
2019-11-07 05:39:56.923 | 1470077 | INFO | brokkr.startup | Interrupted by signal 15; terminating Brokkr
2019-11-07 07:40:29.802 | 43 | INFO | brokkr.startup | Starting Brokkr...
2019-11-16 00:55:32.862 | 753303104 | ERROR | brokkr.sunsaver | ModbusIOException reading register data for /dev/ttyUSB0: Modbus Error: [Input/Output] No Response received from the remote unit/Unable to decode response
2019-11-16 00:55:32.863 | 753303105 | INFO | brokkr.sunsaver | Details: ModbusSerialClient(rtu baud[9600])
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 164, in read_raw_sunsaver_data
    raise register_data
pymodbus.exceptions.ModbusIOException: Modbus Error: [Input/Output] No Response received from the remote unit/Unable to decode response
2019-11-19 11:32:47.311 | 1050737553 | INFO | brokkr.startup | Interrupted by signal 15; terminating Brokkr
2019-11-19 11:34:02.913 | 46 | INFO | brokkr.startup | Starting Brokkr...
2019-12-01 01:09:43.238 | 109 | INFO | brokkr.startup | Starting Brokkr...
2019-12-12 02:51:50.663 | 956527534 | INFO | brokkr.startup | Interrupted by signal 15; terminating Brokkr
2019-12-12 02:52:24.130 | 105 | INFO | brokkr.startup | Starting Brokkr...
2019-12-18 17:44:28.175 | 571924150 | ERROR | brokkr.sunsaver | ModbusIOException reading register data for /dev/ttyUSB0: Modbus Error: [Input/Output] Modbus Error: [Invalid Message] Incomplete message received, expected at least 2 bytes (0 received)
2019-12-18 17:44:28.179 | 571924155 | INFO | brokkr.sunsaver | Details: ModbusSerialClient(rtu baud[9600])
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 165, in read_raw_sunsaver_data
    raise register_data
pymodbus.exceptions.ModbusIOException: Modbus Error: [Input/Output] Modbus Error: [Invalid Message] Incomplete message received, expected at least 2 bytes (0 received)
2019-12-18 17:45:28.166 | 571984142 | ERROR | brokkr.sunsaver | ModbusIOException reading register data for /dev/ttyUSB0: Modbus Error: [Input/Output] Modbus Error: [Invalid Message] Incomplete message received, expected at least 2 bytes (0 received)
2019-12-18 17:45:28.171 | 571984146 | INFO | brokkr.sunsaver | Details: ModbusSerialClient(rtu baud[9600])
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 165, in read_raw_sunsaver_data
    raise register_data
pymodbus.exceptions.ModbusIOException: Modbus Error: [Input/Output] Modbus Error: [Invalid Message] Incomplete message received, expected at least 2 bytes (0 received)
2019-12-18 17:46:28.170 | 572044145 | ERROR | brokkr.sunsaver | ModbusIOException reading register data for /dev/ttyUSB0: Modbus Error: [Input/Output] Modbus Error: [Invalid Message] Incomplete message received, expected at least 2 bytes (0 received)
2019-12-18 17:46:28.170 | 572044146 | INFO | brokkr.sunsaver | Details: ModbusSerialClient(rtu baud[9600])
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 165, in read_raw_sunsaver_data
    raise register_data
pymodbus.exceptions.ModbusIOException: Modbus Error: [Input/Output] Modbus Error: [Invalid Message] Incomplete message received, expected at least 2 bytes (0 received)
2019-12-18 17:47:28.167 | 572104143 | ERROR | brokkr.sunsaver | ModbusIOException reading register data for /dev/ttyUSB0: Modbus Error: [Input/Output] Modbus Error: [Invalid Message] Incomplete message received, expected at least 2 bytes (0 received)
2019-12-18 17:47:28.172 | 572104147 | INFO | brokkr.sunsaver | Details: ModbusSerialClient(rtu baud[9600])
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 165, in read_raw_sunsaver_data
    raise register_data
pymodbus.exceptions.ModbusIOException: Modbus Error: [Input/Output] Modbus Error: [Invalid Message] Incomplete message received, expected at least 2 bytes (0 received)
2019-12-18 17:48:28.167 | 572164142 | ERROR | brokkr.sunsaver | ModbusIOException reading register data for /dev/ttyUSB0: Modbus Error: [Input/Output] Modbus Error: [Invalid Message] Incomplete message received, expected at least 2 bytes (0 received)
2019-12-18 17:48:28.171 | 572164146 | INFO | brokkr.sunsaver | Details: ModbusSerialClient(rtu baud[9600])
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 165, in read_raw_sunsaver_data
    raise register_data
pymodbus.exceptions.ModbusIOException: Modbus Error: [Input/Output] Modbus Error: [Invalid Message] Incomplete message received, expected at least 2 bytes (0 received)
2019-12-18 17:49:28.166 | 572224142 | ERROR | brokkr.sunsaver | ModbusIOException reading register data for /dev/ttyUSB0: Modbus Error: [Input/Output] Modbus Error: [Invalid Message] Incomplete message received, expected at least 2 bytes (0 received)
2019-12-18 17:49:28.171 | 572224146 | INFO | brokkr.sunsaver | Details: ModbusSerialClient(rtu baud[9600])
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 165, in read_raw_sunsaver_data
    raise register_data
pymodbus.exceptions.ModbusIOException: Modbus Error: [Input/Output] Modbus Error: [Invalid Message] Incomplete message received, expected at least 2 bytes (0 received)
2019-12-18 17:50:27.168 | 572283143 | ERROR | brokkr.sunsaver | ModbusIOException reading register data for /dev/ttyUSB0: Modbus Error: [Input/Output] Modbus Error: [Invalid Message] Incomplete message received, expected at least 2 bytes (0 received)
2019-12-18 17:50:27.169 | 572283144 | INFO | brokkr.sunsaver | Details: ModbusSerialClient(rtu baud[9600])
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 165, in read_raw_sunsaver_data
    raise register_data
pymodbus.exceptions.ModbusIOException: Modbus Error: [Input/Output] Modbus Error: [Invalid Message] Incomplete message received, expected at least 2 bytes (0 received)
2019-12-18 17:51:28.166 | 572344142 | ERROR | brokkr.sunsaver | ModbusIOException reading register data for /dev/ttyUSB0: Modbus Error: [Input/Output] Modbus Error: [Invalid Message] Incomplete message received, expected at least 2 bytes (0 received)
2019-12-18 17:51:28.168 | 572344143 | INFO | brokkr.sunsaver | Details: ModbusSerialClient(rtu baud[9600])
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 165, in read_raw_sunsaver_data
    raise register_data
pymodbus.exceptions.ModbusIOException: Modbus Error: [Input/Output] Modbus Error: [Invalid Message] Incomplete message received, expected at least 2 bytes (0 received)
2019-12-18 17:52:28.167 | 572404142 | ERROR | brokkr.sunsaver | ModbusIOException reading register data for /dev/ttyUSB0: Modbus Error: [Input/Output] Modbus Error: [Invalid Message] Incomplete message received, expected at least 2 bytes (0 received)
2019-12-18 17:52:28.168 | 572404143 | INFO | brokkr.sunsaver | Details: ModbusS2019-12-18 18:14:07.194 | 111 | INFO | brokkr.startup | Starting Brokkr...
2020-01-12 02:17:08.224 | 2102581142 | CRITICAL | brokkr.monitor | OSError caught at main level: [Errno 5] Input/output error
2020-01-12 02:17:08.225 | 2102581143 | INFO | brokkr.monitor | Details:
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 75, in start_monitoring
    record_status_data(output_path, verbose=verbose)
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 49, in record_status_data
    status_data = get_status_data()
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 39, in get_status_data
    output_data = item.fn()
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 244, in get_sunsaver_data
    register_data = read_raw_sunsaver_data(**kwargs)
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 160, in read_raw_sunsaver_data
    if mppt_client.connect():
  File "/home/thor/dev/brokkrenv/lib/python3.7/site-packages/pymodbus/client/sync.py", line 481, in connect
    parity=self.parity)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 286, in open
    self._update_dtr_state()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 634, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
OSError: [Errno 5] Input/output error
2020-01-12 02:18:08.221 | 2102641139 | CRITICAL | brokkr.monitor | OSError caught at main level: [Errno 5] Input/output error
2020-01-12 02:18:08.223 | 2102641141 | INFO | brokkr.monitor | Details:
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 75, in start_monitoring
    record_status_data(output_path, verbose=verbose)
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 49, in record_status_data
    status_data = get_status_data()
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 39, in get_status_data
    output_data = item.fn()
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 244, in get_sunsaver_data
    register_data = read_raw_sunsaver_data(**kwargs)
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 160, in read_raw_sunsaver_data
    if mppt_client.connect():
  File "/home/thor/dev/brokkrenv/lib/python3.7/site-packages/pymodbus/client/sync.py", line 481, in connect
    parity=self.parity)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 286, in open
    self._update_dtr_state()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 634, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
OSError: [Errno 5] Input/output error
2020-01-14 18:28:07.213 | 2333640130 | CRITICAL | brokkr.monitor | OSError caught at main level: [Errno 5] Input/output error
2020-01-14 18:28:07.214 | 2333640132 | INFO | brokkr.monitor | Details:
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 75, in start_monitoring
    record_status_data(output_path, verbose=verbose)
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 49, in record_status_data
    status_data = get_status_data()
  File "/home/thor/dev/brokkr/src/brokkr/monitor.py", line 39, in get_status_data
    output_data = item.fn()
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 244, in get_sunsaver_data
    register_data = read_raw_sunsaver_data(**kwargs)
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 160, in read_raw_sunsaver_data
    if mppt_client.connect():
  File "/home/thor/dev/brokkrenv/lib/python3.7/site-packages/pymodbus/client/sync.py", line 481, in connect
    parity=self.parity)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 286, in open
    self._update_dtr_state()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 634, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
OSError: [Errno 5] Input/output error
2020-01-14 18:28:58.991 | 2333691909 | INFO | brokkr.startup | Interrupted by signal 15; terminating Brokkr
2020-01-14 18:31:13.323 | 109 | INFO | brokkr.startup | Starting Brokkr...
2020-01-14 18:55:31.830 | 1458617 | INFO | brokkr.startup | Interrupted by signal 15; terminating Brokkr
2020-01-14 18:55:45.563 | 47 | INFO | brokkr.startup | Starting Brokkr...
2020-01-21 16:43:52.986 | 107 | INFO | brokkr.startup | Starting Brokkr...
2020-01-24 17:08:54.017 | 260701138 | ERROR | brokkr.sunsaver | OSError connecting to charge controller device /dev/ttyUSB0: [Errno 5] Input/output error
2020-01-24 17:08:54.019 | 260701140 | INFO | brokkr.sunsaver | Details: ModbusSerialClient(rtu baud[9600])
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 161, in read_raw_sunsaver_data
    connect_successful = mppt_client.connect()
  File "/home/thor/dev/brokkrenv/lib/python3.7/site-packages/pymodbus/client/sync.py", line 481, in connect
    parity=self.parity)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 286, in open
    self._update_dtr_state()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 634, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
OSError: [Errno 5] Input/output error
2020-01-24 17:09:54.013 | 260761134 | ERROR | brokkr.sunsaver | OSError connecting to charge controller device /dev/ttyUSB0: [Errno 5] Input/output error
2020-01-24 17:09:54.014 | 260761135 | INFO | brokkr.sunsaver | Details: ModbusSerialClient(rtu baud[9600])
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 161, in read_raw_sunsaver_data
    connect_successful = mppt_client.connect()
  File "/home/thor/dev/brokkrenv/lib/python3.7/site-packages/pymodbus/client/sync.py", line 481, in connect
    parity=self.parity)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 286, in open
    self._update_dtr_state()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 634, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
OSError: [Errno 5] Input/output error
2020-01-24 18:37:15.206 | 960088 | ERROR | brokkr.sunsaver | OSError connecting to charge controller device /dev/ttyUSB0: [Errno 5] Input/output error
2020-01-24 18:37:15.208 | 960089 | INFO | brokkr.sunsaver | Details: ModbusSerialClient(rtu baud[9600])
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 161, in read_raw_sunsaver_data
    connect_successful = mppt_client.connect()
  File "/home/thor/dev/brokkrenv/lib/python3.7/site-packages/pymodbus/client/sync.py", line 481, in connect
    parity=self.parity)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 286, in open
    self._update_dtr_state()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 634, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
OSError: [Errno 5] Input/output error
2020-01-24 18:38:15.207 | 1020089 | ERROR | brokkr.sunsaver | OSError connecting to charge controller device /dev/ttyUSB0: [Errno 5] Input/output error
2020-01-24 18:38:15.208 | 1020090 | INFO | brokkr.sunsaver | Details: ModbusSerialClient(rtu baud[9600])
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 161, in read_raw_sunsaver_data
    connect_successful = mppt_client.connect()
  File "/home/thor/dev/brokkrenv/lib/python3.7/site-packages/pymodbus/client/sync.py", line 481, in connect
    parity=self.parity)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 286, in open
    self._update_dtr_state()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 634, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
OSError: [Errno 5] Input/output error
2020-01-24 18:38:36.318 | 1041200 | INFO | brokkr.startup | Interrupted by signal 15; terminating Brokkr
2020-01-24 19:43:42.009 | 47 | INFO | brokkr.startup | Starting Brokkr...
2020-01-25 00:39:46.061 | 17764099 | ERROR | brokkr.sunsaver | ModbusIOException reading register data for /dev/ttyUSB0: Modbus Error: [Input/Output] Modbus Error: [Invalid Message] Incomplete message received, expected at least 2 bytes (0 received)
2020-01-25 00:39:46.062 | 17764100 | INFO | brokkr.sunsaver | Details: ModbusSerialClient(rtu baud[9600])
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 167, in read_raw_sunsaver_data
    raise register_data
pymodbus.exceptions.ModbusIOException: Modbus Error: [Input/Output] Modbus Error: [Invalid Message] Incomplete message received, expected at least 2 bytes (0 received)
2020-01-25 00:41:43.033 | 17881071 | ERROR | pymodbus.client.sync | [Errno 13] could not open port /dev/ttyAMA0: [Errno 13] Permission denied: '/dev/ttyAMA0'
2020-01-25 00:41:43.035 | 17881074 | ERROR | brokkr.sunsaver | Error reading register data: Cannot connect to device /dev/ttyAMA0
2020-01-25 00:41:43.036 | 17881074 | INFO | brokkr.sunsaver | Device info: ModbusSerialClient(rtu baud[9600])
2020-01-25 00:42:43.033 | 17941071 | ERROR | pymodbus.client.sync | [Errno 13] could not open port /dev/ttyAMA0: [Errno 13] Permission denied: '/dev/ttyAMA0'
2020-01-25 00:42:43.036 | 17941074 | ERROR | brokkr.sunsaver | Error reading register data: Cannot connect to device /dev/ttyAMA0
2020-01-25 00:42:43.038 | 17941076 | INFO | brokkr.sunsaver | Device info: ModbusSerialClient(rtu baud[9600])
2020-01-25 00:57:43.042 | 18841080 | ERROR | pymodbus.client.sync | [Errno 13] could not open port /dev/ttyAMA0: [Errno 13] Permission denied: '/dev/ttyAMA0'
2020-01-25 00:57:43.046 | 18841084 | ERROR | brokkr.sunsaver | Error reading register data: Cannot connect to device /dev/ttyAMA0
2020-01-25 00:57:43.048 | 18841086 | INFO | brokkr.sunsaver | Device info: ModbusSerialClient(rtu baud[9600])
2020-01-25 00:58:43.042 | 18901080 | ERROR | pymodbus.client.sync | [Errno 13] could not open port /dev/ttyAMA0: [Errno 13] Permission denied: '/dev/ttyAMA0'
2020-01-25 00:58:43.046 | 18901084 | ERROR | brokkr.sunsaver | Error reading register data: Cannot connect to device /dev/ttyAMA0
2020-01-25 00:58:43.048 | 18901086 | INFO | brokkr.sunsaver | Device info: ModbusSerialClient(rtu baud[9600])
2020-01-25 00:59:43.053 | 18961091 | ERROR | brokkr.sunsaver | OSError connecting to charge controller device /dev/ttyUSB0: [Errno 5] Input/output error
2020-01-25 00:59:43.054 | 18961092 | INFO | brokkr.sunsaver | Details: ModbusSerialClient(rtu baud[9600])
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 161, in read_raw_sunsaver_data
    connect_successful = mppt_client.connect()
  File "/home/thor/dev/brokkrenv/lib/python3.7/site-packages/pymodbus/client/sync.py", line 481, in connect
    parity=self.parity)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 286, in open
    self._update_dtr_state()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 634, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
OSError: [Errno 5] Input/output error
2020-01-25 01:00:43.051 | 19021089 | ERROR | brokkr.sunsaver | OSError connecting to charge controller device /dev/ttyUSB0: [Errno 5] Input/output error
2020-01-25 01:00:43.052 | 19021090 | INFO | brokkr.sunsaver | Details: ModbusSerialClient(rtu baud[9600])
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 161, in read_raw_sunsaver_data
    connect_successful = mppt_client.connect()
  File "/home/thor/dev/brokkrenv/lib/python3.7/site-packages/pymodbus/client/sync.py", line 481, in connect
    parity=self.parity)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 286, in open
    self._update_dtr_state()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 634, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
OSError: [Errno 5] Input/output error
2020-01-25 02:58:43.050 | 26101089 | ERROR | brokkr.sunsaver | OSError connecting to charge controller device /dev/ttyUSB0: [Errno 5] Input/output error
2020-01-25 02:58:43.052 | 26101090 | INFO | brokkr.sunsaver | Details: ModbusSerialClient(rtu baud[9600])
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 161, in read_raw_sunsaver_data
    connect_successful = mppt_client.connect()
  File "/home/thor/dev/brokkrenv/lib/python3.7/site-packages/pymodbus/client/sync.py", line 481, in connect
    parity=self.parity)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 286, in open
    self._update_dtr_state()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 634, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
OSError: [Errno 5] Input/output error
2020-01-25 02:59:43.051 | 26161089 | ERROR | brokkr.sunsaver | OSError connecting to charge controller device /dev/ttyUSB0: [Errno 5] Input/output error
2020-01-25 02:59:43.052 | 26161091 | INFO | brokkr.sunsaver | Details: ModbusSerialClient(rtu baud[9600])
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 161, in read_raw_sunsaver_data
    connect_successful = mppt_client.connect()
  File "/home/thor/dev/brokkrenv/lib/python3.7/site-packages/pymodbus/client/sync.py", line 481, in connect
    parity=self.parity)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 286, in open
    self._update_dtr_state()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 634, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
OSError: [Errno 5] Input/output error
2020-01-25 03:00:33.542 | 26211580 | INFO | brokkr.startup | Interrupted by signal 15; terminating Brokkr
2020-01-25 03:04:33.675 | 47 | INFO | brokkr.startup | Starting Brokkr...
2020-01-25 03:04:36.045 | 2417 | ERROR | pymodbus.client.sync | [Errno 2] could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0'
2020-01-25 03:04:36.046 | 2418 | WARNING | brokkr.sunsaver | Successfully reset charge controller device /dev/ttyUSB0; original error OSError: [Errno 5] Input/output error
2020-01-25 03:04:36.047 | 2419 | INFO | brokkr.sunsaver | Device info: {'device': '/dev/ttyUSB0', 'name': 'ttyUSB0', 'description': 'FT230X Basic UART', 'hwid': 'USB VID:PID=0403:6015 SER=DM00N0H5 LOCATION=1-1.3', 'vid': 1027, 'pid': 24597, 'serial_number': 'DM00N0H5', 'location': '1-1.3', 'manufacturer': 'FTDI', 'product': 'FT230X Basic UART', 'interface': None, 'usb_device_path': '/sys/devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb1/1-1/1-1.3', 'device_path': '/sys/devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb1/1-1/1-1.3/1-1.3:1.0/ttyUSB0', 'subsystem': 'usb-serial', 'usb_interface_path': '/sys/devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb1/1-1/1-1.3/1-1.3:1.0'}
Traceback (most recent call last):
  File "/home/thor/dev/brokkr/src/brokkr/sunsaver.py", line 179, in read_raw_sunsaver_data
    connect_successful = mppt_client.connect()
  File "/home/thor/dev/brokkrenv/lib/python3.7/site-packages/pymodbus/client/sync.py", line 481, in connect
    parity=self.parity)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 286, in open
    self._update_dtr_state()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 634, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
OSError: [Errno 5] Input/output error
2020-01-25 03:04:36.054 | 2427 | ERROR | brokkr.sunsaver | Error reading register data: Cannot connect to device /dev/ttyUSB0
2020-01-25 03:04:36.055 | 2427 | INFO | brokkr.sunsaver | Device info: ModbusSerialClient(rtu baud[9600]); Port info: {'device': '/dev/ttyUSB0', 'name': 'ttyUSB0', 'description': 'FT230X Basic UART', 'hwid': 'USB VID:PID=0403:6015 SER=DM00N0H5 LOCATION=1-1.3', 'vid': 1027, 'pid': 24597, 'serial_number': 'DM00N0H5', 'location': '1-1.3', 'manufacturer': 'FTDI', 'product': 'FT230X Basic UART', 'interface': None, 'usb_device_path': '/sys/devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb1/1-1/1-1.3', 'device_path': '/sys/devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb1/1-1/1-1.3/1-1.3:1.0/ttyUSB0', 'subsystem': 'usb-serial', 'usb_interface_path': '/sys/devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb1/1-1/1-1.3/1-1.3:1.0'}
2020-01-25 03:39:55.497 | 2121869 | INFO | brokkr.startup | Interrupted by signal 15; terminating Brokkr
2020-01-25 03:42:28.317 | INFO | brokkr.start | Starting Brokkr version 0.3.0.dev0... (T+80 ms)
2020-01-25 03:42:28.318 | INFO | brokkr.start | Starting monitoring system... (T+81 ms)
2020-01-25 03:42:28.319 | INFO | brokkr.start | Monitor arguments: {} (T+81 ms)
2020-01-25 03:42:28.330 | INFO | brokkr.config.main | Rendered config: {'version': 1, 'general': {'ip_sensor': '10.10.10.1', 'output_path': PosixPath('/home/thor/data')}, 'monitor': {'interval_log_s': 60, 'interval_sleep_s': 1, 'na_marker': 'NA', 'output_path': PosixPath('/home/thor/data/monitoring'), 'sensor': {'hs_port': 8084, 'hs_timeout_s': 2, 'ping_timeout_s': 1}, 'sunsaver': {'pid_list': [24597], 'port': '', 'start_offset': 8, 'unit': 1}}, 'site': {'name_prefix': 'hamma', 'number': '', 'description': 'Test Sensor (Default)'}} (T+92 ms)
2020-01-25 03:42:28.335 | INFO | brokkr.monitoring.monitor | Ensuring monitoring directory at: /home/thor/data/monitoring (T+97 ms)
2020-01-25 04:12:08.860 | WARNING | brokkr.start | Interrupted by signal 15; terminating Brokkr (T+1780623 ms)
2020-01-25 04:12:13.922 | 53 | INFO | brokkr.startup | Starting Brokkr...
2020-01-28 22:48:10.786 | 114 | INFO | brokkr.startup | Starting Brokkr...
2020-01-28 22:48:12.035 | 1363 | ERROR | brokkr.sunsaver | Error reading Sunsaver data: No serial devices found.
2020-01-28 22:49:11.792 | 61120 | ERROR | brokkr.sunsaver | Error reading Sunsaver data: No serial devices found.
2020-01-28 22:50:11.793 | 121120 | ERROR | brokkr.sunsaver | Error reading Sunsaver data: No serial devices found.
2020-01-28 22:51:11.804 | 181132 | ERROR | brokkr.sunsaver | Error reading Sunsaver data: No serial devices found.
2020-01-28 22:52:11.804 | 241132 | ERROR | brokkr.sunsaver | Error reading Sunsaver data: No serial devices found.
2020-01-28 22:53:11.804 | 301132 | ERROR | brokkr.sunsaver | Error reading Sunsaver data: No serial devices found.
2020-01-28 22:54:11.804 | 361132 | ERROR | brokkr.sunsaver | Error reading Sunsaver data: No serial devices found.
2020-01-28 22:55:11.804 | 421132 | ERROR | brokkr.sunsaver | Error reading Sunsaver data: No serial devices found.
2020-01-28 22:56:11.804 | 481132 | ERROR | brokkr.sunsaver | Error reading Sunsaver data: No serial devices found.
2020-01-28 22:57:11.804 | 541132 | ERROR | brokkr.sunsaver | Error reading Sunsaver data: No serial devices found.
2020-01-28 22:58:11.804 | 601132 | ERROR | brokkr.sunsaver | Error reading Sunsaver data: No serial devices found.
2020-01-28 22:59:11.794 | 661122 | ERROR | brokkr.sunsaver | Error reading Sunsaver data: No serial devices found.
2020-01-28 23:00:11.804 | 721132 | ERROR | brokkr.sunsaver | Error reading Sunsaver data: No serial devices found.
2020-01-28 23:01:11.796 | 781124 | ERROR | brokkr.sunsaver | Error reading Sunsaver data: No serial devices found.
2020-01-28 23:02:11.808 | 841136 | ERROR | brokkr.sunsaver | Error reading Sunsaver data: No serial devices found.
2020-01-28 23:03:11.808 | 901136 | ERROR | brokkr.sunsaver | Error reading Sunsaver data: No serial devices found.
2020-01-28 23:04:11.804 | 961132 | ERROR | brokkr.sunsaver | Error reading Sunsaver data: No serial devices found.
2020-01-28 23:05:11.804 | 1021132 | ERROR | brokkr.sunsaver | Error reading Sunsaver data: No serial devices found.
2020-01-28 23:06:11.808 | 1081136 | ERROR | brokkr.sunsaver | Error reading Sunsaver data: No serial devices found.
2020-01-28 23:07:11.808 | 1141135 | ERROR | brokkr.sunsaver | Error reading Sunsaver data: No serial devices found.
2020-01-28 23:08:11.808 | 1201136 | ERROR | brokkr.sunsaver | Error reading Sunsaver data: No serial devices found.
2020-01-28 23:09:11.794 | 1261122 | ERROR | brokkr.sunsaver | Error reading Sunsaver data: No serial devices found.
2020-01-28 23:10:11.804 | 1321132 | ERROR | brokkr.sunsaver | Error reading Sunsaver data: No serial devices found.
2020-01-28 23:11:11.804 | 1381131 | ERROR | brokkr.sunsaver | Error reading Sunsaver data: No serial devices found.
2020-01-28 23:12:11.808 | 1441135 | ERROR | brokkr.sunsaver | Error reading Sunsaver data: No serial devices found.
2020-01-28 23:13:11.804 | 1501132 | ERROR | brokkr.sunsaver | Error reading Sunsaver data: No serial devices found.
2020-01-28 23:14:11.804 | 1561132 | ERROR | brokkr.sunsaver | Error reading Sunsaver data: No serial devices found.
2020-01-28 23:15:11.808 | 1621136 | ERROR | brokkr.sunsaver | Error reading Sunsaver data: No serial devices found.
2020-01-28 23:16:11.804 | 1681132 | ERROR | brokkr.sunsaver | Error reading Sunsaver data: No serial devices found.
2020-01-28 23:17:11.804 | 1741132 | ERROR | brokkr.sunsaver | Error reading Sunsaver data: No serial devices found.
2020-01-28 23:18:11.808 | 1801136 | ERROR | brokkr.sunsaver | Error reading Sunsaver data: No serial devices found.
2020-01-28 23:19:11.794 | 1861122 | ERROR | brokkr.sunsaver | Error reading Sunsaver data: No serial devices found.
2020-01-28 23:20:11.804 | 1921132 | ERROR | brokkr.sunsaver | Error reading Sunsaver data: No serial devices found.
2020-01-28 23:21:11.804 | 1981132 | ERROR | brokkr.sunsaver | Error reading Sunsaver data: No serial devices found.
2020-01-28 23:22:11.804 | 2041132 | ERROR | brokkr.sunsaver | Error reading Sunsaver data: No serial devices found.
2020-01-28 23:23:11.808 | 2101136 | ERROR | brokkr.sunsaver | Error reading Sunsaver data: No serial devices found.
2020-01-28 23:24:11.804 | 2161132 | ERROR | brokkr.sunsaver | Error reading Sunsaver data: No serial devices found.
2020-01-28 23:25:11.804 | 2221132 | ERROR | brokkr.sunsaver | Error reading Sunsaver data: No serial devices found.
2020-01-28 23:26:11.808 | 2281136 | ERROR | brokkr.sunsaver | Error reading Sunsaver data: No serial devices found.
2020-01-28 23:27:11.804 | 2341132 | ERROR | brokkr.sunsaver | Error reading Sunsaver data: No serial devices found.
2020-01-28 23:28:11.804 | 2401132 | ERROR | brokkr.sunsaver | Error reading Sunsaver data: No serial devices found.
2020-01-28 23:29:11.793 | 2461121 | ERROR | brokkr.sunsaver | Error reading Sunsaver data: No serial devices found.
2020-01-28 23:30:11.808 | 2521136 | ERROR | brokkr.sunsaver | Error reading Sunsaver data: No serial devices found.
2020-01-28 23:31:11.804 | 2581132 | ERROR | brokkr.sunsaver | Error reading Sunsaver data: No serial devices found.
2020-01-28 23:32:11.804 | 2641132 | ERROR | brokkr.sunsaver | Error reading Sunsaver data: No serial devices found.
2020-01-28 23:33:11.808 | 2701136 | ERROR | brokkr.sunsaver | Error reading Sunsaver data: No serial devices found.
2020-01-28 23:34:11.804 | 2761132 | ERROR | brokkr.sunsaver | Error reading Sunsaver data: No serial devices found.
2020-01-28 23:35:11.804 | 2821132 | ERROR | brokkr.sunsaver | Error reading Sunsaver data: No serial devices found.
2020-01-28 23:36:11.808 | 2881136 | ERROR | brokkr.sunsaver | Error reading Sunsaver data: No serial devices found.
2020-01-28 23:37:11.804 | 2941132 | ERROR | brokkr.sunsaver | Error reading Sunsaver data: No serial devices found.
2020-01-28 23:38:11.804 | 3001132 | ERROR | brokkr.sunsaver | Error reading Sunsaver data: No serial devices found.
2020-01-28 23:39:11.795 | 3061123 | ERROR | brokkr.sunsaver | Error reading Sunsaver data: No serial devices found.
2020-01-28 23:40:11.808 | 3121136 | ERROR | brokkr.sunsaver | Error reading Sunsaver data: No serial devices found.
2020-01-28 23:41:11.804 | 3181132 | ERROR | brokkr.sunsaver | Error reading Sunsaver data: No serial devices found.
2020-01-28 23:42:11.804 | 3241132 | ERROR | brokkr.sunsaver | Error reading Sunsaver data: No serial devices found.
2020-01-28 23:43:11.808 | 3301136 | ERROR | brokkr.sunsaver | Error reading Sunsaver data: No serial devices found.
2020-01-28 23:44:11.804 | 3361132 | ERROR | brokkr.sunsaver | Error reading Sunsaver data: No serial devices found.
2020-01-28 23:45:11.804 | 3421132 | ERROR | brokkr.sunsaver | Error reading Sunsaver data: No serial devices found.
2020-01-28 23:46:11.808 | 3481136 | ERROR | brokkr.sunsaver | Error reading Sunsaver data: No serial devices found.
2020-01-28 23:47:11.804 | 3541132 | ERROR | brokkr.sunsaver | Error reading Sunsaver data: No serial devices found.
2020-01-28 23:48:11.804 | 3601132 | ERROR | brokkr.sunsaver | Error reading Sunsaver data: No serial devices found.
2020-01-28 23:49:11.794 | 3661122 | ERROR | brokkr.sunsaver | Error reading Sunsaver data: No serial devices found.
2020-01-28 23:50:11.808 | 3721136 | ERROR | brokkr.sunsaver | Error reading Sunsaver data: No serial devices found.
2020-01-28 23:51:11.804 | 3781132 | ERROR | brokkr.sunsaver | Error reading Sunsaver data: No serial devices found.
2020-01-28 23:52:11.804 | 3841132 | ERROR | brokkr.sunsaver | Error reading Sunsaver data: No serial devices found.
2020-01-28 23:53:11.808 | 3901135 | ERROR | brokkr.sunsaver | Error reading Sunsaver data: No serial devices found.
2020-01-28 23:54:11.804 | 3961132 | ERROR | brokkr.sunsaver | Error reading Sunsaver data: No serial devices found.
2020-01-28 23:55:11.804 | 4021132 | ERROR | brokkr.sunsaver | Error reading Sunsaver data: No serial devices found.
2020-01-28 23:56:11.808 | 4081135 | ERROR | brokkr.sunsaver | Error reading Sunsaver data: No serial devices found.
2020-01-29 00:24:01.825 | 114 | INFO | brokkr.startup | Starting Brokkr...
2020-01-29 00:24:03.081 | 1370 | ERROR | brokkr.sunsaver | Error reading Sunsaver data: No serial devices found.
2020-01-29 00:25:02.830 | 61119 | ERROR | brokkr.sunsaver | Error reading Sunsaver data: No serial devices found.
2020-01-29 00:26:02.830 | 121120 | ERROR | brokkr.sunsaver | Error reading Sunsaver data: No serial devices found.
2020-01-29 00:27:02.841 | 181130 | ERROR | brokkr.sunsaver | Error reading Sunsaver data: No serial devices found.
2020-01-29 00:28:02.841 | 241130 | ERROR | brokkr.sunsaver | Error reading Sunsaver data: No serial devices found.
2020-01-29 00:29:02.841 | 301130 | ERROR | brokkr.sunsaver | Error reading Sunsaver data: No serial devices found.
2020-01-29 00:30:02.841 | 361131 | ERROR | brokkr.sunsaver | Error reading Sunsaver data: No serial devices found.
2020-01-29 00:31:02.841 | 421130 | ERROR | brokkr.sunsaver | Error reading Sunsaver data: No serial devices found.
2020-01-29 00:32:02.841 | 481130 | ERROR | brokkr.sunsaver | Error reading Sunsaver data: No serial devices found.
2020-01-29 00:33:02.841 | 541130 | ERROR | brokkr.sunsaver | Error reading Sunsaver data: No serial devices found.
2020-01-29 00:34:02.841 | 601130 | ERROR | brokkr.sunsaver | Error reading Sunsaver data: No serial devices found.
